### ISSUE TITLE
W3C validation: Keyword copyright is not registered.

### ISSUE THREAD

**Issue by thomaszbz** [mblaschke/TYPO3-metaseo#10]
w3c validation against HTML5 reports an error:
"Bad value copyright for attribute name on element meta: Keyword copyright is not registered."

Hint: there is a dcterms.rights, dcterms.rightsHolder, dcterms.dateCopyrighted  Meta extension. Maybe these should be used instead.

References:
http://validator.w3.org/
https://html.spec.whatwg.org/multipage/semantics.html#standard-metadata-names
https://wiki.whatwg.org/wiki/MetaExtensions

**Comment by thomaszbz** [comment]
Same applies for dc.rights:
"Bad value DC.Rights for attribute name on element meta: Keyword dc.rights is not registered."
Tested version was 1.0.5

**Comment by mblaschke** [comment]
Will check this for MetaSEO 2.0.0 (currently in develop-Branch)

**Comment by mblaschke** [comment]
Fixed in develop Branch.

Please check this version :)
