### ISSUE TITLE
W3C Validation: document-wide default language is obsolete

### ISSUE THREAD

**Issue by thomaszbz** [mblaschke/TYPO3-metaseo#11]
w3c validation against HTML5 reports an error
"Using the meta element to specify the document-wide default language is obsolete. Consider specifying the language on the root element instead."

This comes from the "meta http-equiv="content-language" content="de"", which can be safely removed, according to the w3c recommendation. Instead, the language can be set with "html lang="de"" which is already done.

References:
http://validator.w3.org/
https://html.spec.whatwg.org/multipage/semantics.html#standard-metadata-names
https://wiki.whatwg.org/wiki/MetaExtensions

**Comment by thomaszbz** [comment]
Plus, DC.Language is already implemented in v1.0.5. However, W3C validation reports an extra error:
"The scheme attribute on the meta element is obsolete. Use only one scheme per field, or make the scheme declaration part of the value."

This comes from the "scheme="NISOZ39.50""

**Comment by mblaschke** [comment]
Will be removed in MetaSEO 2.0.0 (currently in develop Branch)

**Comment by mblaschke** [comment]
I've removed both: http-equiv="content-language" AND DC.language
