### ISSUE TITLE
[POSSIBLE-ENHANCEMENT] possibility to automitically create redirects for pagename changes / speaking url segment changes

### ISSUE THREAD

**Issue by AndreasA** [mblaschke/TYPO3-metaseo#112]
Not sure if this is the best extension for this but in theory it is SEO related because the search engines would recognize a 301 and provide the corresponding content.

An option to automatically create redirects when renaming pages would be a nice addition.
However, this would actually only be applicable in combination with realurl currently (I think there are plans to move speaking URLs into the core though) and would actually be in combination with e.g. changing realurl unique-aliases etc.

**Comment by thomaszbz** [comment]
301 redirects are perfectly handled by extensions which provide speaking urls, e.g. realurl.

**Comment by AndreasA** [comment]
Yes, they are but you still have to create them manually. No auto-option. There are quite a lot of systems that provide auto-redirect if you change e.g. the page name from the old to the new without the user having to add it manually.
Furthermore, as far as I know realurl intends to drop redirects with 2.x

But in any case, I guess it would be good to wait and see with what the TYPO3 core comes up regarding speaking URLs. Not sure, if v8 LTS or v7 LTS though.
