### ISSUE TITLE
[TASK] replace or update Ext.JS

### ISSUE THREAD

**Issue by thomaszbz** [mblaschke/TYPO3-metaseo#114]
Currently, we use ExtJS 3.4.1.1 as of current develop branch 19e2754a269c8607ce0ab0a3f8b80c85dc23e7eb.

In TYPO3 CMS 7.4 core, the use of ExtJS was replaced:

"On the JavaScript side, Prototype.js, script.acul.ous and ExtCore have been completely removed. All JavaScript code that was dependent on these frameworks has been migrated to use jQuery and RequireJS. This is part of the effort to streamline the JavaScript code shipped with the core, and unify the JavaScript frameworks in use to improve not only the extensibility but also the performance on the client side."

We need to investigate if we have to replace our ExtJS 3.4.1.1 code. It could happen that this no longer works in TYPO3 7.4.

We need to decide if we want to replace ExtJS with jQuery. Plus, we could eventually update the ExtJS version. In case ExtJS 3.4.1.1 still works in TYPO3 7.4 we could also decide to do nothing at all until EOL of TYPO3 6.2.

Plus, we need to deal with the question if whatever we do is compatible to TYPO3 CMS 6.2.

References:
http://typo3.org/news/article/announcing-typo3-74-nothing-is-impossible/

**Comment by mblaschke** [comment]
We could provider our own ExtJS 3.4.1.1 code but migrate to other solutions in future or just update to ExtJS 6.

**Comment by thomaszbz** [comment]
I like the idea to migrate to jQuery, just because TYPO3 does. However, I think this is something we should do after 2.0.0 is released, if ever possible. The question is if it's worth an update to ExtJS 6 if we rewrite everything after TYPO3 6.2's EOL. We could also give ExtJS 6 a try, just to see how much work it is and then decide again if we use it. If it's not a lot of work we could just do it (maybe even for 2.0.0) and migrate to jQuery later.

Plus, when we migrate to jQuery we need to decide if we want to depend on the jQuery version used by TYPO3. There could be breaking changes in the future in jQuery which we need to address when supporting multiple TYPO3 versions. In a way, it's the same problem we are currently faced with TYPO3's ExtJS version.

If we can maintain our jQuery code in a backwards compatible manner, that would clearly be the best option in the future.

**Comment by thomaszbz** [comment]
RequireJS made it into TYPO3 6.1, so we should be able to use it in 6.2 and later.

https://forge.typo3.org/projects/typo3cms-core/repository/revisions/b9129bf2d5374935760e1ac33bb7dbf1874b3ac0

**Comment by thomaszbz** [comment]
Here's the breaking change documentation about removed ExtJS (forge-68001):

https://wiki.typo3.org/TYPO3.CMS/Releases/7.4/Breaking#Breaking:_.2368001_-_Removed_ExtJS_Core_and_ExtJS_Adapters

Affected Installations

    Instances that use ExtCore in the TYPO3 Frontend
    Extensions that use <f:be.container> with an ExtJS Adapter
    Extensions that use the PageRenderer object directly to load custom ExtJS or ExtCore.

**Comment by thomaszbz** [comment]
As of current master, TYPO3 CMS 7.5-dev 8f540ffbf880691a17d6d4c3ca4f184abba84d22, ExtJS 3.4.1.1 is still available and our backend is still running smoothly (with latest 7.5.0 compat patches).

**Comment by thomaszbz** [comment]
For instance, there is nothing to do. The backend still works with mid-7.5.0.

In case we need an alternative for Ext.JS 3.4.1.1 we can still reopen this issue later.

**Comment by thomaszbz** [comment]
Got an info from core-devs about this:

* TYPO3 CMS v7 _final_ will be shipped with ExtJS 3.4.1.1 again and there will be _no_ update of ExtJS.
* ExtJS will be _dropped_ in the core of TYPO3 v8.
