### ISSUE TITLE
TYPO3 Ext. Repository - MetaSEO "No Manual"

### ISSUE THREAD

**Issue by AMartinNo1** [mblaschke/TYPO3-metaseo#115]
Hello,

today I've heard of your extension and want to give it a try. Ofc I checked the details on the extension detailpage in TYPO3 Extension Repository for a manual but there is no link available. In the README.md (https://github.com/mblaschke/TYPO3-metaseo/blob/develop/README.md) you link to a manual - https://docs.typo3.org/typo3cms/extensions/metaseo/

For upcoming people who notices this extension a direct link to the manual would be helpful.

Best wishes
AMartinNo1

**Comment by thomaszbz** [comment]
I can confirm that on http://typo3.org/extensions/repository/view/metaseo there is an entry

    Manual    Not available

Instead, "Not available", there should be a link to http://typo3.org/extensions/repository/view/metaseo .

**Comment by thomaszbz** [comment]
I was told that there were general issues for most extensions.

I pinged @spoonerweb on #t3o on slack.

**Comment by thomaszbz** [comment]
Works again. Whatever it was, there has been no change by t3o. @spoonerweb thinks it's a caching issue and it should be fixed forever.

Anyways, thanks for reporting this issue.
