### ISSUE TITLE
Metatags contain only the values from the default language

### ISSUE THREAD

**Issue by thomaszbz** [mblaschke/TYPO3-metaseo#122]
by @NicoMoehring via https://forge.typo3.org/issues/63978

I have a website which is translated into six languages. Every page has a description and keywords. These attributes are different for every language. The SEO/MetaTags module in the backend shows the correct values for each language (see attached image).

If i open a page in the frontend in a specific language the content is translated but the metatags are still in the default language (see attached image). I would expect that the metatags are also translated.

The problem seems to be in the MetatagPart.php.
The values of the metatags are fetched by calls like this:

```
$cObj->stdWrap(
    $tsSetupSeo['conf.']['description_page'],
    $tsSetupSeo['conf.']['description_page.']
)
```

These calls return the default language value even if a different language id is set.
https://forge.typo3.org/attachments/download/28129/Backend.jpg
https://forge.typo3.org/attachments/download/28130/Frontend.jpg

**Comment by thomaszbz** [comment]
Answer by @mblaschke 
Do you have any custom TypoScript configuration?
It's working without any custom configuration.

**Comment by thomaszbz** [comment]
We still use the line of code as of current develop 19e2754a269c8607ce0ab0a3f8b80c85dc23e7eb:

        $tmp = $this->cObj->stdWrap(
            $this->tsSetupSeo['conf.']['description_page'],
            $this->tsSetupSeo['conf.']['description_page.']
        );

**Comment by fdrewes** [comment]
I have the same problem.
In my case the correct language will be rendered with this code - use getData() instead of stdWrap():

`$tmp = $cObj->getData('field : ' . $tsSetupSeo['conf.']['description_page.']['field']);`

**Comment by thomaszbz** [comment]
Thank you for the feedback and your suggestion.

Do I get it right that the problem is that the ``content=`` properties are not translated in the frontend?

Can you please send me

* TYPO3 version you use
* MetaSEO version you use
* PHP version you use
* TypoScript in case you do something special here.

**Comment by fdrewes** [comment]
Of course.
- TYPO3 6.2.14
- MetaSEO 1.0.8
- PHP 5.5.28

TypoScript would be too extensive. The language config part is like this:

`# Deutsch`
`config.linkVars = L`
`config.sys_language_uid = 0`
`config.language = de`
`config.locale_all = de_DE`
`config.htmlTag_langKey = de-DE`
`config.sys_language_mode = strict`

`# Englisch`
`[globalVar = GP:L=1]`
`config.linkVars = L`
`config.sys_language_uid = 1`
`config.language = en`
`config.locale_all = en_IE`
`config.htmlTag_langKey = en-IE`
`[global]`

**Comment by thomaszbz** [comment]
Test against 6.2.14, MetaSEO 1.0.8, PHP 5.6, RealURL enabled:

TypoScript:

    # Deutsch
    config.linkVars = L
    config.sys_language_uid = 0
    config.language = de
    config.locale_all = de_DE
    config.htmlTag_langKey = de-DE
    config.sys_language_mode = strict
    
    # Englisch
    [globalVar = GP:L=1]
    config.linkVars = L
    config.sys_language_uid = 1
    config.language = en
    config.locale_all = en_IE
    config.htmlTag_langKey = en-IE
    [global]

    # Default PAGE object:
    page = PAGE
    # Define output for typeNum=0, the default type.
    page.typeNum = 0
    page.10 = TEXT
    page.10.value = HELLO WORLD!

Added translated page, then I edit keywords in _page-properties_

I get:

    172.17.0.77/?id=7
    <meta name="keywords" content="Deutsche Schlüsselwörter">

    172.17.0.77/?id=7&L=1
    <meta name="keywords" content="English Keywords">

This is just to see if it works in general (could be a workaround). Next, I will see if it works when I edit translation in MetaSEO.

**Comment by fdrewes** [comment]
Another suggestion:

When I change the way how to declare the variable $cObj, I will get the correct translation with the usage of stdWrap().

Changing from:
`$cObj     = $GLOBALS['TSFE']->cObj;`

to:
`$cObj = \TYPO3\CMS\Core\Utility\GeneralUtility::makeInstance('TYPO3\CMS\Frontend\ContentObject\ContentObjectRenderer');`
`$cObj->start($GLOBALS['TSFE']->page, 'pages');`

will do it for me without modifying the rest of the code.

I don't know why, but $GLOBALS['TSFE']->cObj seems to be always in default language in my configuration.

**Comment by thomaszbz** [comment]
``TYPO3\CMS\Frontend\ContentObject\ContentObjectRenderer`` is not marked as Singelton in Typo3 core 6.2.14. I'm not sure if this is a valid fix.

* Are you testing with your root page (as demonstrated by @NicoMoehring in the pictures)?
* Please tell me which extensions you have installed. Would it be possible to disable them (on a non-production test system!) and see what happens?

If this is a bug I would pretty much like to fix it because it's an important feature of MetaSEO. But I need to reproduce it first.

**Comment by fdrewes** [comment]
`$cObj     = $GLOBALS['TSFE']->cObj;`
`$cObj->start($GLOBALS['TSFE']->page, 'pages');`
will also do it.

I cleared all caches, even from InstallTool.

The Extensions I could deactivate (with no effect) are:
- RealURL (1.13.3)
- wt_spamshield (1.3.1)

Other important known extensions are:
- flux (7.2.1)
- fluidpages (3.3.1)
- fluidcontent (4.3.1)
- vhs (2.3.3)

**Comment by thomaszbz** [comment]
start() is also a bit offensive:

	/**
	 * Class constructor.
	 * Well, it has to be called manually since it is not a real constructor function.
	 * So after making an instance of the class, call this function and pass to it a database record and the tablename from where the record is from. That will then become the "current" record loaded into memory and accessed by the .fields property found in eg. stdWrap.
	 *
	 * @param array $data The record data that is rendered.
	 * @param string $table The table that the data record is from.
	 * @return void
	 * @todo Define visibility
	 */
	public function start($data, $table = '') {

I guess somewhere in your setup the language is set to the default page. Could you provide some debug info which language is set when you perform an ``?id=123&L=1``?

**Comment by thomaszbz** [comment]
I reproduced it!

Same as before, but this time with all the extensions installed:

    RealURL (1.13.3)
    wt_spamshield (1.3.1)
    flux (7.2.1)
    fluidpages (3.3.1)
    fluidcontent (4.3.1)
    vhs (2.3.3)

I was running autoconfiguration in the extension manager for each of the extension.

    CSS Styled Content (css_styled_content)
    Fluid: (Optional) default ajax configuration (fluid)
    Main Settings (wt_spamshield)
    formhandler (wt_spamshield)
    Default TS (form)
    MetaSEO (metaseo)

Now I get

    <meta name="keywords" content="Deutsche Schlüsselwörter Änderung in PageSEO-MetaTags">
    <meta http-equiv="content-language" content="de">

    <meta name="keywords" content="Deutsche Schlüsselwörter Änderung in PageSEO-MetaTags">
    <meta http-equiv="content-language" content="en">

**Comment by thomaszbz** [comment]
Ok, some googling told me:

* This is a known problem #3 and Markus was already investigating on this.
* Already reported to fluidpages: https://github.com/FluidTYPO3/fluidpages/issues/270

Which instantly renders it a duplicate of #3.

**Comment by thomaszbz** [comment]
TYPO3's PageRenderer is not affected by this:

	public function setLanguage($lang) {
		if($lang != 'en') {
			throw new \Exception('the language was set to ' . $lang);
		}

is never thrown.

**Comment by thomaszbz** [comment]
Classified as bug, as we can reproduce it (via #122), although we still don't know the reason for it. Fluidpages project does not feel responsible, so it could still be a bug in the core or in metaseo.

This issue might be a duplicate of #3

**Comment by verdure-tietz** [comment]
I think, this is probably related to https://forge.typo3.org/issues/23736

The stdWrap'ed TypoScript "field" attribute (as cited in https://github.com/mblaschke/TYPO3-metaseo/issues/122#issue-100158622 ) doesn't seem to support pages_language_overlay

**Comment by thomaszbz** [comment]
@verdure-tietz Thanks for the hint. If it's a bug in TYPO3, we need a workaround for metaseo and/or a bugfix for TYPO3.

Would you please post back to the forge issue that the bug still is present in recent typo3 versions?  To my knowledge, internationalization is a main feature of an enterprise CMS. The forge bug is open for 6 years now.

Even a core bugfix in 8.x/7.6 would not help us if the bug is not fixed for 6.2, so maybe we need a workaround anyways. (overwrite something with XClass maybe).

I'd be happy to see this bug closed. If you can provide more details or reproduce it more in detail, together with forge-issue 23736, I'd be happy to hear from you.

**Comment by verdure-tietz** [comment]
@thomaszbz latest post in forge issue 23736 already says that "As far as I can see it is still present on bot 8.2-dev and 7.6.6"

I am running TYPO3 6.2 for this project. For now I switched to seo_basics, I'm afraid...

A workaround would be to select the page from a repository directly (which should result in the language overlay) instead of getting data.field from the cObj. The field name could still be configured via TypoScript of course.

**Comment by MrMooky** [comment]
I know this is quite old, but we're still having issues with that. The following does not use the translation:

```
20 = TEXT
20.field = tx_metaseo_pagetitle
```

This does output the correct translation:

```
20 = TEXT
#20.field = tx_metaseo_pagetitle
20.stdWrap.noTrimWrap = |
20.stdWrap.ifEmpty.cObject = TEXT
20.stdWrap.ifEmpty.cObject.data = TSFE:page|tx_metaseo_pagetitle
```
