### ISSUE TITLE
W3C Validation: up link

### ISSUE THREAD

**Issue by thomaszbz** [mblaschke/TYPO3-metaseo#13]
w3c validation against HTML5 reports an error:
"Bad value up for attribute rel on element link: The string up is not a registered keyword."

This comes from "link rel="up" href=..."

Hint: start, next, priv, canonical are documented in the MetaExtensions Wiki and pass W3C validation. I suggest to add "up" to the wiki (if this is widely used) and comment it out in metaseo as long as the W3C validation fails.

References:
http://validator.w3.org/
https://html.spec.whatwg.org/multipage/semantics.html#standard-metadata-names
https://wiki.whatwg.org/wiki/MetaExtensions

Tested version is v1.0.5

**Comment by thomaszbz** [comment]
up: "was in HTML3 - but dropped in HTML4. Explicitly dropped from HTML5 interim draft yet permitted for external registry".

References:
http://microformats.org/wiki/existing-rel-values#HTML5_link_type_extensions
http://lists.w3.org/Archives/Public/public-html/2011Feb/att-0481/issue-118-decision.html

**Comment by thomaszbz** [comment]
verified against c7d23d776efb2ee866a12fdc2f60cda588cdf852

**Comment by thomaszbz** [comment]
It seems there was an update of validator.w3c.org. The error of this ticket still persists.

**Comment by thomaszbz** [comment]
Is there a reason to still keep the up link? I guess nobody uses HTML3 and in later versions, it's dropped.

**Comment by thomaszbz** [comment]
PR #36 for that.

**Comment by mblaschke** [comment]
Merged :)
