### ISSUE TITLE
[Feature] Select Protocol for Canonical

### ISSUE THREAD

**Issue by al-Iskandar** [mblaschke/TYPO3-metaseo#141]
If you do not enter a URL as canonical in the page properties, metaseo puts always the URL, the page is called.
If you offer a page as http and as https, metaseo uses always the URL you called (http://example.com/page by http and https://example.com/page by https) for causes of SEO it would be helpfull, if there would be a constant for the site template which allows to select whether Metaseo shall use always http oder https as the protocol of the canonical.

**Comment by thomaszbz** [comment]
This feature request looks valid to me: Using one URL (with only _one_ protocol) is what the canonical URL meta tag is all about.

Use case would be that one want's to offer both protocols with no https-only strategy. That makes sense at least during a transition towards a https-only strategy.

There should be an additional canonical config variable to go for http or https when nothing else is defined.

Hence, we need to make sure that visitors do not get bounced back (301'd via TYPO3's protocol selection in the page properties) to the other protocol when entering the canonical URL.

For canonical Url generation, we should

* Prio 1: Go for TYPO3's protocol selection in the page properties when defined (!= default)
* Prio 2: Go for preference via metaseo config in case it is specified
* Prio 3 (Fallback): Go for current protocol (as we do now)

Comments on this are welcome.

**Comment by thomaszbz** [comment]
09e2499 implements this feature for the canonical URLs.

@al-Iskandar Do you want to test it before it is merged?

**Comment by al-Iskandar** [comment]
Sorry, had no time for looking, but I can test it. Is it implemented in the actual development-branch or what I have to change?

**Comment by thomaszbz** [comment]
@al-Iskandar You can checkout ccf8e22 with

    git remote add thomaszbz https://github.com/thomaszbz/TYPO3-metaseo.git
    git remote update thomaszbz
    git checkout --track -b dev/141-canonical-fallback-protocol

I assume you were already testing the patch?
