### ISSUE TITLE
Extend support for OpenGraph images

### ISSUE THREAD

**Issue by c2po** [mblaschke/TYPO3-metaseo#172]
Hi,

actually there is already some support for OpenGraph images - what is great!

But for out of the box support there should be an additional field added to pages where editors could add a special image for facebook. (images in ressources should be used for something different.)

Also opengraph has some extended syntax ("og:image:width") which is actually not supported by metaseo typoscript but which could speed up facebook shares ("Using these tags will specify the image to the crawler so that it can render it immediately without having to asynchronously.").

**Comment by thomaszbz** [comment]
OpenGraph support got introduced via merge of a feature branch in April 2015 via 26283781584b647dfe0fa2ea205057c6e0bccdee . Contributions are welcome in case you want to speed up the process.

**Comment by thomaszbz** [comment]
Page properties now have a new section:

![grafik](https://cloud.githubusercontent.com/assets/11200727/25398858/c6620220-29ed-11e7-9f9b-bc606dc6415a.png)
