### ISSUE TITLE
sitemap generate relative path not uris

### ISSUE THREAD

**Issue by nixmomo** [mblaschke/TYPO3-metaseo#177]
Hi,
metaseo genereates in sitemaps all uris relative, without domain

    <url>
        <loc>http:///var/www/typo3/faq/</loc>
        <lastmod>2015-09-15T14:07:20+02:00</lastmod>
        <priority>0.50</priority>
    </url>

How can i fix this to use Domain Name and not this stupid relative paths...

**Comment by thomaszbz** [comment]
I'm wondering why you would have ``/var/www/typo3`` in your URI and why there's three slashes after ``http:``. I assume that something on your system is configured really strange: Make sure you access typo3 via http and via network (using a web server). Make sure that you don't expose the path of your wwwroot to visitors.

As far as I see, metaseo generates URIs like

    <loc>https://www.example.com/speaking/path/</loc>

in sitemaps which is by far not a relative path.

In case you think your configuration is fine you'd have to tell us how exactly your setup looks like. In case your setup should be fine then the output you presented would mean that you have hit a bug. For the moment, I'm very courious that metaseo should have produced that, at least using a commonly used system config/web server config.

**Comment by nixmomo** [comment]
the 3 backslashes comes from http:// + relative path beginning with /var ...

My Webserver Configs are all ok and the domain is working fine... its a dev solution, not in prod yet but it is planned...
I think its a bug in metaseo, what config du you need?

**Comment by thomaszbz** [comment]
* operating system
* web server and version
* vhost configuration
* URI of application root (e.g. ``http://127.0.0.1``)
* URI of a browsable example page (which you can query in your browser), e.g. ``http://127.0.0.1/?id=4``
* URI of your sitemap, e.g. ``http://127.0.0.1/?id=2&type=841132` or ``http://127.0.0.1/?id=2&type=841133``
* What's the origin of the output you sent us? Is it the webserver (output you got via http) or did you send us output from sitemap data which metaseo stored to the file system?

**Comment by nixmomo** [comment]
hi,
the problem is fixed... i postet the output of the generated sitemap via http.
The Problem was static file cache..
