### ISSUE TITLE
W3C validation: schema.dc and schema.dcterms

### ISSUE THREAD

**Issue by thomaszbz** [mblaschke/TYPO3-metaseo#18]
schema.dc and schema.dcterms seem not to be registered in HTML5.

    <link rel="schema.dcterms" href="http://purl.org/dc/terms/">

returns an error:

    Bad value schema.DCTERMS for attribute rel on element link: The string schema.dcterms is not a registered keyword.

A proposed solution could be:

    <html lang="de" itemscope itemtype="http://schema.org/LocalBusiness">
    <head prefix="og: http://ogp.me/ns#; dcterms: http://purl.org/dc/terms">

with

    
    <meta property="dcterms:title" content="Website Title" />
    <meta property="dcterms:description" content="Website Description" />
    
    <meta property="og:title" content="Website Title" />
    <meta property="og:description" content="Website Description" />
    
    <meta itemprop="name" content="Website Title" />
    <meta itemprop="description" content="Website Description" />

This avoids validation errors. However, I'm not sure if dublin core is evaluated that way by search engines etc. Plus,

    <meta name="DCTERMS.title" content="...">

passes W3C validation without errors, because DCTERMS.* is registered by itself. So, the link could eventually be removed (although the link is required according to https://wiki.whatwg.org/wiki/MetaExtensions )

Suggestion:
- Either use the proposed solution or comment out the existing link until this is registered and used in W3C validation.
- Eventually, a specific behaviour for HTML5 is necessary (Compared to HTML4 or XHTML).

References:
http://www.aljtmedia.com/blog/resolving-html5-dublin-core-microdata-validation-issues/
https://wiki.whatwg.org/wiki/MetaExtensions

**Comment by thomaszbz** [comment]
It seems there was an update of validator.w3c.org. The error still persists for

    <link rel="schema.dcterms" href="http://purl.org/dc/terms/">

**Comment by mblaschke** [comment]
Should we wait of this issue? schema.dcterms is valid for xhtml but currently not for html5.

**Comment by thomaszbz** [comment]
I'm undiceded what the intention of W3C is here. Right now, I did not read about a statement saying that it's explicitly forbidden. Maybe it was just forgotten.

It could be possible that there will be another update for the validator. However, I can't see a contact-button besides the error in the validator. This could mean that it's final.

**Comment by thomaszbz** [comment]
There is a W3C bug report:

https://www.w3.org/Bugs/Public/show_bug.cgi?format=multiple&id=22520

**Comment by thomaszbz** [comment]
For instance, PR #37 gives me a clean HTML5 validation (together with #13)

**Comment by thomaszbz** [comment]
PR #37 is merged already. Thus, this issue can be closed.

**Comment by thomaszbz** [comment]
The doctype has changed from html_5 to html5 since 4.5:
https://forge.typo3.org/issues/27661

Plus, after some debugging, 

    $GLOBALS['TSFE']->config['config']['doctype']

returns null. There's something wrong in current develop 50ca181ec09d2922c41145286d8e548d696dd7b5

**Comment by thomaszbz** [comment]
At least in 6.2, it should be

    $GLOBALS['TSFE']->config['config']['config.']['doctype']

instead. PR #46 for that.

References: http://docs.typo3.org/typo3cms/TyposcriptReference/Setup/Config/Index.html#doctype
