### ISSUE TITLE
Sitemap does not contain pages with valid cHash

### ISSUE THREAD

**Issue by pantainer** [mblaschke/TYPO3-metaseo#182]
Hi,

i'm having some extensions in my site who all get a valid cHash for their URLs, but only some of them are included in the sitemap.xml. The pages are all listed within the "Indexed TYPO3 Pages". Using Version 1.0.8 with TYPO3 6.2.15.

Any idea what could be the problem?

Thx!

**Comment by thomaszbz** [comment]
Would you please try it out the latest version from the pre-2.0.0 develop branch (on a non-production system)? It should still work with TYPO3 6.2.x.

**Comment by pantainer** [comment]
It works perfectly with the develop branch. Thanks!
