### ISSUE TITLE
Wrong parameters in cObjGetSingle call

### ISSUE THREAD

**Issue by danilovq** [mblaschke/TYPO3-metaseo#187]
Second parameter must be the array with TypoScript properties for the content object. It was broken in 59b8a306e7749df30c174714fb690ce04365b20c

**Comment by thomaszbz** [comment]
59b8a30 only changes syntax with behaviour unchanged.

Instead, this bug is older:

Bug was introduced in df23b84953b635cbad68753d6e4bf64a70fbfb8b, presumably as a merge error which was not correctly resolved via 002259c1248cbb6db0a8e556e6420633cb483b2c
