### ISSUE TITLE
Add expire-date to sitemap (from metatags)

### ISSUE THREAD

**Issue by mblaschke** [mblaschke/TYPO3-metaseo#21]
Add an expiry date (based on metatags) for sitemap entries

**Comment by mblaschke** [comment]
Implemented first part in 598e3f6

**Comment by mblaschke** [comment]
Refactoring done in 51ac49d2a3356e790d5b8cef664c9c6daff0e0dd

**Comment by thomaszbz** [comment]
What's the meaning of tx_metaseo_sitemap.expire?

**Comment by mblaschke** [comment]
Each entry will be stored with a expiry date (eg. for garbage collection).

Next step is to implement a possibility to set the expire date from an extension to set a custom expire date for one entry. Got this idea from one customer :)
