### ISSUE TITLE
Please register package on Packagist

### ISSUE THREAD

**Issue by cedricziel** [mblaschke/TYPO3-metaseo#213]
Doing so allows for easier integration in more advanced projects and stable dev dependencies.

Thank you :)

**Comment by mblaschke** [comment]
MetaSEO is registered in TYPO3 satis at https://composer.typo3.org/satis.html#!/metaseo

Because it's a TYPO3 only extension is it really necessary to register this project also on Packagist?

**Comment by cedricziel** [comment]
Yes. It's a composer dependency in the first place. As such, I expect it to be on packagist.

**Comment by mblaschke** [comment]
Done and thanks :)
