### ISSUE TITLE
Opengraph tags cannot be overriden by the connector

### ISSUE THREAD

**Issue by cedricziel** [mblaschke/TYPO3-metaseo#214]
In a plugin I grab the Connector and feed it with additional opengraph information:

```
/** @var MetaseoConnector $metaseoConnector */
$metaseoConnector = GeneralUtility::makeInstance(MetaseoConnector::class);
$metaseoConnector->setOpenGraphTag('title', $tour->getTitle() . ' ' . $this->settings['suffixTitle']);
```

But the MetaTagPart only renders the page title. (`Details`, as it's a Plugin detail page)

Deleting the og:title altogether for that page helps, but is harsh.

**Comment by thomaszbz** [comment]
Thanks for the bug report and for the fix. For the record:

1dba4a5 from #215 seems to be equivalent to the behaviour of `setMetaTag` which is also used for an override.

The key `'meta:og'` is already available in the connector. That means the feature exists, but it has an unexpected behaviour by not overriding og tags. Indeed, that renders this issue a bug.

I'm going to reproduce the issue more in detail and if the fix actually fixes the issue (although it already looks good ;-) )

**Comment by cedricziel** [comment]
I'm pretty sure it already existed, that's why I implemented it the way I did ^^

**Comment by thomaszbz** [comment]
For the moment I'm wondering if it's really an override in both cases (`setMetaTag`/`setOpenGraphTag`). 1dba4a5 looks more like a fallback while `connector->collectMetaDataFromConnector()` really does an override via the `Connector`. Instead, we should have consistency here.

**Comment by cedricziel** [comment]
I'm open for suggestions

**Comment by thomaszbz** [comment]
In documentation, the only occurence of the string `Connector` is here:

> `plugin.metaseo.pageTitle.caching` Enables caching of page title. If the page is fully cacheable you don't have to enable this option. If you use USER_INTs and one USER plugin changes page title (eg. via Connector) than this is not working because the output of the USER plugin is cached and the Connector not called again with the second hit. The caching fixes that issue.

Actually this does not help to figure out how the connector should behave here in terms of priority.

I guess that `setMetaTag`/`setOpenGraphTag` should at least have the same behaviour in terms of priority (fallback or override). That in mind, the patch should override og tags via the connector. Maybe we get some input from @mblaschke on this?

**Comment by thomaszbz** [comment]
I got it wrong: There's the difference:

`setMetaTag()` stores in `$storeMeta['meta']`and serves as default
`setCustomMetaTag()` stores in `$storeMeta['custom']`and is used for the override.

Respectively, `setOpenGraphTag()` serves as a default while there is no `setCustomOpenGraphTag()` implemented yet in `Connector`. The question now would be which case is yours?

**Comment by thomaszbz** [comment]
$metaTagPart->advMetaTags() also "does" something with `$storeMeta['meta:og']` from the connector.

                //todo: $advMetaTagList not in use
                $advMetaTagList = array_merge($advMetaTagList, $storeMeta['meta:og']);

Actually it does not, because `$advMetaTagList` is unused because it is instantly overridden via

$advMetaTagList = DatabaseUtility::getList($query);

a few lines later and in any case. So there is no way, the existing implementation used data from the connector via  `$storeMeta['meta:og']`.

Maybe we should fix the bug at this place. At least this is where it was intended to be implemented originally. I already added the todo some time ago because PhpStorm was complaining.

**Comment by thomaszbz** [comment]
State of d006238 is just to illustrate how I think the existing code was meant to work, with bugs removed respectively:

* Process OpenGraph meta tags from the connector via `advMetaTags()`
* Override meta tags which were generated via `generateOpenGraphMetaTags` by using the same array keys as `generateOpenGraphMetaTags`
* Suppress any OpenGraph meta tags from advanced meta tags coming from the _database_ in case OpenGraph meta tags are available via _connector_ (I'm not sure if this is a good idea, but this is what the existing code came up with)
* In case there is no OpenGraph meta tags available via _connector_, then process OpenGraph advanced meta tags from the _database_ with correct properties and correct 'og.'-prefixed array keys. Therefore, overwriting Tags from `generateOpenGraphMetaTags`
* 'og:'-Prefix OpenGraph meta tags from the Connector for consistency with `generateOpenGraphMetaTags`

**Comment by nabossha** [comment]
@cedricziel would you be please provide a simple code-snippet how you included the Connector in your plugin's Controller? I'm currently struggling to set meta-tags on a detail-page and would like to learn how to implement the Connector like you did in your snippet

**Comment by cedricziel** [comment]
@nabossha That's the actual example taken from my application. I call the following function from my actions:

```php
    // imported the connector class with `use Metaseo\Metaseo\Connector as MetaseoConnector;`
    /**
     * @param Tour $tour
     */
    protected function addTourMetaInformation(Tour $tour)
    {
        /** @var MetaseoConnector $metaseoConnector */
        $metaseoConnector = GeneralUtility::makeInstance(MetaseoConnector::class);

        if ($tour->getDescriptionSeo() !== '') {
            $metaseoConnector->setMetaTag('description', $tour->getDescriptionSeo());
        } else {
            $metaseoConnector->setMetaTag('description', $tour->getDescription());
        }

        $metaseoConnector->setMetaTag('title', $tour->getTitle() . ' ' . $this->settings['suffixTitle']);
        $metaseoConnector->setOpenGraphTag('title', $tour->getTitle() . ' ' . $this->settings['suffixTitle']);

        if ($tour->getTeaserImage()) {
            $metaseoConnector->setOpenGraphTag('image', rtrim($this->settings['absoluteBaseUrl'], '/')
            . '/' . ltrim($tour->getTeaserImage()->getOriginalResource()->getPublicUrl(), '/'));
        }
    }
```

**Comment by nabossha** [comment]
@cedricziel  thanks a lot for this sample - that really helped me to get into it!

**Comment by thomaszbz** [comment]
Testing with current develop 2.0.1-pre 162bd42f0e7a232234e28b68301c07ed048601d7

## Reproduce with:

        $connector->setMetaTag('testMetaKey', 'testMetaValue'); //expected: no output
        $connector->setCustomMetaTag('testCustomMetaKey', 'testCustomMetaValue'); //expected: custom output
        $connector->setOpenGraphTag('title', 'titleContent'); //expected: overwrite og:title
        $connector->setOpenGraphTag('newOgKey', 'newOgContent'); //expected: no Output


## Expected:

    <meta property="og:title" content="titleContent">
    <meta rel="testCustomMetaKey" href="testCustomMetaValue">

## Actual Result:

    <meta property="og:title" content="z">
    <meta rel="testCustomMetaKey" href="testCustomMetaValue">

So in fact, `og:title` is not overridden. Which reproduces this issue.

Current implementation does not allow to set custom OG keys (will be ignored). This should remain as is, unless there is a new function `setCustomOpenGraphTag()` for consistency

**Comment by thomaszbz** [comment]
Testing with my patch d006238:

## Expected:

    <meta property="og:title" content="titleContent">
    <meta rel="testCustomMetaKey" href="testCustomMetaValue">

## Actual Result:

<meta property="og:title" content="titleContent">
<meta property="og:newOgKey" content="newOgContent">
<meta rel="testCustomMetaKey" href="testCustomMetaValue">

So d006238 it is overwriting `og:title` and has correct property names, but it allows to add custom open graph tags which is inconsistent to `setMetaTag()/setCustomMetaTag()` as we don't have a `setCustomOpenGraphTag()` yet. Plus would it have wrong property names (rel/href) for an OpenGraph tag. Therefore, d006238 is not a valid patch.

**Comment by thomaszbz** [comment]
Testing with my patch 28a1799:

## Expected:

    <meta property="og:title" content="titleContent">
    <meta rel="testCustomMetaKey" href="testCustomMetaValue">

## Actual Result:

    <meta property="og:title" content="titleContent">
    <meta rel="testCustomMetaKey" href="testCustomMetaValue">

That matches quite well.

**Comment by thomaszbz** [comment]
#215 suggests to have custom opengraph tags, which is a new feature to metaseo (as tested on develop 2.0.1-pre 162bd42).

d006238 already had this feature using `setOpenGraphTag()` but I removed it intentionally via 28a1799. 28a1799 is just for the bugfix.

Having custom opengraph tags can be classified as a new feature.

**Comment by thomaszbz** [comment]
Testing with 3c3d167

## Reproduce with:

        $connector->setMetaTag('testMetaKey', 'testMetaValue'); //expected: no output
        $connector->setCustomMetaTag('testCustomMetaKey', 'testCustomMetaValue'); //expected: custom output
        $connector->setOpenGraphTag('title', 'titleContent'); //expected: overwrite og:title
        $connector->setOpenGraphTag('newOgKey', 'newOgContent'); //expected: no Output
        $connector->setCustomOpenGraphTag('newCustomOgKey', 'newCustomOgContent'); //expected: custom output


## Expected:

    <meta property="og:title" content="titleContent">
    <meta property="og:newCustomOgKey" content="newCustomOgContent">
    <meta rel="testCustomMetaKey" href="testCustomMetaValue">

## Actual Result:

    <meta property="og:title" content="titleContent">
    <meta property="og:newCustomOgKey" content="newCustomOgContent">
    <meta rel="testCustomMetaKey" href="testCustomMetaValue">

I made it so that custom og tags overwrite tags from the database (via `advMetaTags`) selectively, meaning that

- `setOpenGraphTag()` suppresses all the OG output that comes from the database via `advMetaTags` while
- `setCustomOpenGraphTag()` _selectively_ suppresses the OG output that comes from the database via `advMetaTags` only when there is an exact match by the tag key. That allows to just enhance a tag.
