### ISSUE TITLE
page title doesn't appear

### ISSUE THREAD

**Issue by blueamerican** [mblaschke/TYPO3-metaseo#22]
typo3 6.2.9, metaseo 1.0.6

i cannot set the page title over the extension. the constant "page title" is activated

**Comment by mblaschke** [comment]
Is this a new bug appeared in 1.0.6? Or was this bug also present in 1.0.5?

**Comment by blueamerican** [comment]
sorry i think i found the reason:
config.noPageTitle = 2
version was 1.0.5
