### ISSUE TITLE
Make metaseo compatible to custom page types

### ISSUE THREAD

**Issue by thomaszbz** [mblaschke/TYPO3-metaseo#231]
Posted by  @birgerstoeckelmann for PR #230 :

Make metaseo compatible to custom page types (not only using doktype 1,4 in page tree view). Adding typoscript configuration general.allowedDoktypes and changes to PageSeoDao class to use this simple configuration.

**Comment by thomaszbz** [comment]
@birgerstoeckelmann Thanks for contribution and patch.

The patch is not valid against TYPO3 6.2, which we still support. It must be compatible against PHP5.3 to make it into metaseo (2.1 presumably) in the near future. E. g. `ObjectManager::class` syntax is not yet available in PHP 5.3. Should be easy to backport, unless you use newer features from TYPO3 7.6. You can set the PHP version in your IDE (e.g. PhpStorm) to see if syntax check complains (so there's no need to install an old PHP version just for that).

If this patch is not compatible with TYPO3 6.2 at all because of new features used from 7.6, then I'll schedule it for the 3.0 release which will drop support for 6.2. Just let me know. For 3.0, we'll refactor towards all the new features we get via PHP 5.5 (and previous versions).

By custom doktypes, you mean doktypes from extensions?

Naming in config: `general` might be too general. Could you suggest a better naming?

What's the main goal of this issue? Do you want metaseo to handle all doktypes which might contain content?

Maybe we should add allow other extensions to hook new doktypes into metaseo by themselves. There should also be a way to _add_ new doktypes and not only set them once via configuration.

However, I like the idea.

**Comment by birgerstoeckelmann** [comment]
@thomaszbz Thanks for your quick response - you are right, I will fix my patch to make it valid against TYPO3 6.2 and PHP 5.3.

The main goal of this feature is to list pages with a different doktype than 1 or 4 (which is hardcoded in the PageSeoDao class) in the metaseo web module. We created an extension which simply adds a "Product Page" with doktype 91 and a custom page icon. This page type is a normal page, showing up in the frontend with content elements, gets indexed by solr and so on. But it is not visible in the backend module of metaseo. So we can not edit meta information for these pages.

Maybe `general` can by omitted? So `allowedDoktypes` would be configured on the first configuration level.

Extension could already add doktypes to this value with 
`plugin.metaseao.allowedDoktypes := addToList(91) `
in their typoscript setup!?

Perhaps `allowedDoktypes` should be `listDoktypes` or something like that.

**Comment by birgerstoeckelmann** [comment]
@thomaszbz Just saw, that you can edit pages with different doktypes by clicking on them directly. But they are not listed when selecting a parent page, so multi-editing of pages with custom page types is not possible due to the fact that the tree is rendered with pages of doktype 1 and 4. Right?

**Comment by thomaszbz** [comment]
`general`: I'd say that `allowedDoktypes` is a variable which offers functionality for `other` extensions. Why not call it `interact`, `external`, `interface`, `api`, `extensions`, etc. ? This would open a new class of variables for _other_ extensions to interact with metaseo.

Maybe you can bring your extension to not set this variable directly but to hook in somehow (as I already posted)? I'm not sure if it's a good idea to let other extensions break metaseo's namespace in terms of config.

If the SQL only loads doktype 1 and 4, then it's the only ones we handle right now. Yes.

**Comment by thomaszbz** [comment]
But you are right: `addToList()` should do the job if it works and if it's usable by other constants without conflict. Any other approach is overcomplicating things.

I'd go for `plugin.metaseao.extensibility.allowedDoktypes`

**Comment by thomaszbz** [comment]
@birgerstoeckelmann The new variable should also be added to documentation.

Please also add yourself to the list of contributors in `Documentation/Introduction/Index.rst`.

**Comment by birgerstoeckelmann** [comment]
Hi Thomas,
finally I fixed my first commit to support PHP 5.3 and Extbase 6. Tested with TYPO3 7 and 6.
Could you please check my second commit in pull request?
Best regards, Birger

**Comment by thomaszbz** [comment]
Thanks for the patch and thanks for backporting against 6.2

Would be great to have a little test case or maybe your extension is online (so that I can use it for testing the patch)? Otherwise I'd have to write some test code myself (I'm not speaking of phpunit tests here).

**Comment by birgerstoeckelmann** [comment]
I would like to send you two urls to 6.2.19 and 7.6.4 TYPO3 test systems.

Could I use your contact form on 2bis10.de<http://2bis10.de> or info[at]2bis10.de<http://2bis10.de> email for this?


Am 01.04.2016 um 10:30 schrieb Thomas Mayer <notifications@github.com<mailto:notifications@github.com>>:


Thanks for the patch and thanks for backporting against 6.2

Would be great to have a little test case or maybe your extension is online (so that I can use it for testing the patch)? Otherwise I'd have to write some test code myself (I'm not speaking of phpunit tests here).

**Comment by thomaszbz** [comment]
Of course, you can use the contact form. Should be encrypted all the way through.

**Comment by thomaszbz** [comment]
ok, on the 6.2 instance, I opened `?id=6` and it made it into the sitemap (was not there before).

Looks good at that point, but I can't look into the code via TYPO3-backend (and play around with it).

**Comment by birgerstoeckelmann** [comment]
Ok, then you have to set up your own TYPO3 and clone https://github.com/birgerstoeckelmann/TYPO3-metaseo, I guess. Can't give you FTP access to our server, it's only internal...

**Comment by thomaszbz** [comment]
Your commit is not the issue, I simply add another git-remote for your PR, using my [test setup](https://github.com/thomaszbz/native-dockerfiles-typo3).

But to test the modified connector, I need another extension that somehow uses metaseo's connector.

**Comment by birgerstoeckelmann** [comment]
Hello Thomas,

finally I created an extension for testing the new Metaseo extensibility connector.

https://github.com/birgerstoeckelmann/bm-metaseotest

Please install this extension in TYPO3 7.6 and add the TypoScript template after Metaseo's template file.

The extension simply adds a custom page type named "Product" and adds it's doktype (91) to the new allowedDoktypes list of Metaseo.

Thanks and kind regards,
Birger




Am 01.04.2016 um 13:36 schrieb Thomas Mayer <notifications@github.com<mailto:notifications@github.com>>:


Your commit is not the issue, I simply add another git-remote for your PR, using my test setup<https://github.com/thomaszbz/native-dockerfiles-typo3>.

But to test the modified connector, I need another extension that somehow uses metaseo's connector.

**Comment by thomaszbz** [comment]
Great. I'll come back to that later (mid-May at best because of limited time). Maybe @mblaschke can test/merge it in the meantime.

**Comment by thomaszbz** [comment]
@birgerstoeckelmann could you please counter test feature/custom-pagetype? I already did the changes which were necessary, just did I not test if it actually still works yet. Would you? E.g. with a

    composer require mblaschke/metaseo:dev-feature/custom-pagetype

**Comment by thomaszbz** [comment]
That works great.
![auswahl_261](https://cloud.githubusercontent.com/assets/11200727/25396900/9e514f04-29e6-11e7-8e29-a0a7c636fa42.png)
