### ISSUE TITLE
disableMetaTag doesn't work

### ISSUE THREAD

**Issue by evgeniag** [mblaschke/TYPO3-metaseo#232]
Connector `disableMetaTag` function set null value.

```
public static function disableMetaTag($key)
{
    $key = (string)$key;
    self::$store['meta'][$key] = null;
}
```

But value is trimmed and compared with null on the identity in `\Metaseo\Metaseo\Page\Part\MetatagPart::collectMetaDataFromConnector`. But trim will return empty string in this case.

```
foreach ($storeMeta['meta'] as $metaKey => $metaValue) {
        $metaValue = trim($metaValue);
        if ($metaValue === null) {
            // Remove meta
            unset($this->tsSetupSeo[$metaKey]);
        } elseif (!empty($metaValue)) {
            $this->tsSetupSeo[$metaKey] = $metaValue;
        }
}
```

That's why impossible to disable meta tag.

**Comment by thomaszbz** [comment]
Thanks for reporting this.

Indeed, the `trim()` leads to the problem at https://github.com/mblaschke/TYPO3-metaseo/blob/ccf8e2236c8cbabf9ef0f40c2606a60f3e43ab2b/Classes/Page/Part/MetatagPart.php#L781
