### ISSUE TITLE
Allow more than 50 entries in Sitemap Backend Module

### ISSUE THREAD

**Issue by PanadeEdu** [mblaschke/TYPO3-metaseo#236]
Currently the Sitemap Module in the TYPO3 Backend seems to have a hard limit of 50.
However when manipulating larger datasets, for example to quickly assign new rules or manipulate a batch of entries, it can be time consuming going in steps of 50 entries.

Give an option to increase the number of listed entries on one page.
This way the Backend User can decide what is suitable for him.

**Comment by thomaszbz** [comment]
4615326 was tested against 7.6.10-dev. @PanadeEdu would you like to test against 6.2?

**Comment by ecentral** [comment]
Thx for this patch. I testet it on TYPO3 6.2.29 and it works like a charm.
