### ISSUE TITLE
Hide untranslated pages in sitemap

### ISSUE THREAD

**Issue by kimchristiansen** [mblaschke/TYPO3-metaseo#238]
This issue is still not fixed:

https://forge.typo3.org/issues/45853
When the option 'hidePagesIfNotTranslatedByDefault' is activated through the install tool, typo3 throws a 404 error when a user tries to access a page which is not translated.
But this page, lets say german and english version exists, AND all other combinations of language key & page url are published to the sitemap.

**Comment by thomaszbz** [comment]
Please tell us which version of metaseo and TYPO3 you were using.

**Comment by kimchristiansen** [comment]
I am using TYPO3 6.2.22 and metaseo 2.0.0

**Comment by thomaszbz** [comment]
Reproduced with TYPO3 7.6.14, metaseo 2.0.1.

I used 3 languages:
- L=0: Default language (english)
- L=1: German
- L=2: French

I created a page in default language(L=0), but translated to German (L=1) only:
![auswahl_073](https://cloud.githubusercontent.com/assets/11200727/21075536/10f981a8-bf15-11e6-9b6a-1ec0e4063d46.png)


After http-requesting all three languages, this is what metaseo's sitemap shows:
![auswahl_072](https://cloud.githubusercontent.com/assets/11200727/21075538/1d03efce-bf15-11e6-8de7-cdce6d5386d2.png)

Note that just by requesting L=2, there's an entry for French although the page never got translated to french.

**Comment by discotizer** [comment]
Hi there,

i'm the original poster. 404 there meant simply that the translation was not created in the backend, so that the then called URL from the sitemap should lead to a 404 page.

**Comment by thomaszbz** [comment]
@discotizer got it. I tested without `hidePagesIfNotTranslatedByDefault` enabled. With or without this setting, we need to get non-existing entries out of the sitemap, so that does not really change something. Iin terms of SEO, 404's might be even safer to avoid duplicate content. Google sorts that out then, it's just that it eventually produces a lot of entries in Google's search console.

**Comment by thomaszbz** [comment]
@kimchristiansen @discotizer would you like to test PR #319 ?

With the patch set applied, untranslated entries should not make it into metaseo's index any more.

**Comment by thomaszbz** [comment]
Related: https://github.com/dmitryd/typo3-realurl/issues/313

The bug in RealUrl is still open as of RealUrl 2.1.9
