### ISSUE TITLE
Configuration for editors to set via page attributes noindex?

### ISSUE THREAD

**Issue by Toccamonium** [mblaschke/TYPO3-metaseo#239]
Hi, thanks for this useful extensions. Question: did I miss something, but I actually need a TScript snippet which reacts on editors input for pages to set noindex/nofollow, etc. How can this be achieved? Right now I'm setting this manually via tmpl on the existing page.

regards
Florian

**Comment by thomaszbz** [comment]
Could you please explain your requirement more in detail?

- Do you want your TypoScript to set noindex/nofollow depending on editors' input? Which input
- Do you want your TypoScript to read the noindex/nofollow (set by editors) and do some other fancy stuff? That would simplify your question to "How can I read noindex/nofollow from TypoScript?".

**Comment by Toccamonium** [comment]
It seems, that I found an solution here: https://jweiland.net/typo3/codebeispiele/typoscript/seiten-von-suchmaschinensuche-ausschliessen.html

Well, in contao the editor has an select to choose what he/she needs: https://www.dropbox.com/s/hfpzhrovck5mbs2/01-06-_2016_15-30-29.png?dl=0 and the selected option will be placed in the page header.

I'm using 2.0.0.

**Comment by thomaszbz** [comment]
Great. So I guess you got it solved.
