### ISSUE TITLE
Copying a root page throws an error

### ISSUE THREAD

**Issue by timwehrmann** [mblaschke/TYPO3-metaseo#247]
Hi Markus,

when I try to copy a rootpage, there is an error message displayed that says _"[1.3.-1]: Attempt to insert record on a page that can't store record type"_. The reason is, that on the page is a hidden record of type "tx_metaseo_setting_root", which is not allowed to be placed on pages.

However, if I delete the record from the page, the copy process does not throw an error.

**Information about the system**
- TYPO3 7.6.9
- MetaSEO 2.0.0

**Screenshots**
If I remove the "hideTable" from the TCA, I see the record on folders:
![bildschirmfoto 2016-06-09 um 17 09 19](https://cloud.githubusercontent.com/assets/6337709/15937093/df494950-2e6d-11e6-8f29-3b7c5e0b0a0e.png)

... but not on pages:
![bildschirmfoto 2016-06-09 um 17 09 43](https://cloud.githubusercontent.com/assets/6337709/15937095/e1d08f94-2e6d-11e6-90f3-5d8bdb22b43a.png)

On the page I want to copy, the record is there anyway:
![bildschirmfoto 2016-06-09 um 17 09 53](https://cloud.githubusercontent.com/assets/6337709/15937097/e4438aba-2e6d-11e6-88fb-9c729f39937c.png)

So it fails when I try to copy it:
![bildschirmfoto 2016-06-09 um 17 10 08](https://cloud.githubusercontent.com/assets/6337709/15937102/e684ef76-2e6d-11e6-834e-b292292a0f5c.png)

**Comment by thomaszbz** [comment]
Btw.: It would be great if TYPO3 CMS could output the _name_ of the record type to users. If you want, you could file an issue via typo3-forge. But that's another story.

The error is thrown by TYPO3 core, presumably:

https://github.com/TYPO3/TYPO3.CMS/blob/TYPO3_6-2/typo3/sysext/core/Classes/DataHandling/DataHandler.php#L3211

https://github.com/TYPO3/TYPO3.CMS/blob/TYPO3_7-6/typo3/sysext/core/Classes/DataHandling/DataHandler.php#L3439

It is thrown when the corresponding table for the record is not allowed:

        // Check if table is allowed on destination page
        if ($destPid >= 0 && !$this->isTableAllowedForThisPage($destPid, $table)) {

which leads us to 

    /**
     * Checks if a table is allowed on a certain page id according to allowed tables set for the page "doktype" and its [ctrl][rootLevel]-settings if any.
    public function isTableAllowedForThisPage($page_uid, $checkTable)
    {
        $page_uid = (int)$page_uid;
        $rootLevelSetting = (int)$GLOBALS['TCA'][$checkTable]['ctrl']['rootLevel'];
        // Check if rootLevel flag is set and we're trying to insert on rootLevel - and reversed - and that the table is not "pages" which are allowed anywhere.
        if ($checkTable !== 'pages' && $rootLevelSetting !== -1 && ($rootLevelSetting xor !$page_uid)) {
            return false;
        }
        $allowed = false;
        // Check root-level
        if (!$page_uid) {
            if ($this->admin || BackendUtility::isRootLevelRestrictionIgnored($checkTable)) {
                $allowed = true;
            }
        } else {
            // Check non-root-level
            $doktype = $this->pageInfo($page_uid, 'doktype');
            $allowedTableList = isset($GLOBALS['PAGES_TYPES'][$doktype]['allowedTables'])
                ? $GLOBALS['PAGES_TYPES'][$doktype]['allowedTables']
                : $GLOBALS['PAGES_TYPES']['default']['allowedTables'];
            $allowedArray = GeneralUtility::trimExplode(',', $allowedTableList, true);
            // If all tables or the table is listed as an allowed type, return TRUE
            if (strpos($allowedTableList, '*') !== false || in_array($checkTable, $allowedArray, true)) {
                $allowed = true;
            }
        }
        return $allowed;
    }

We need to investigate which part of the function returns `false` and why this is the case and if this is somehow intended behaviour (with the alternative of mismatch in terms of root pages metaseo knows of).

Workaround from @timwehrmann:

- delete record of type tx_metaseo_setting_root before copy operation
- => no error any more.

Did I get you right that this is a valid workaround for the problem?

Did you use special doktypes other than page? E.g. like separator or even custom doktypes?

**Comment by timwehrmann** [comment]
Hi Thomas,

first of all: Thank you for your very fast response. :-)

And yes, this workaround works. But I wonder: Why just not enable this data record on normal pages?

I also know now, how the record came there: As far as I can tell, the record is placed using the "Control Center" module in the SEO section. If I click there on a root page, that data record is created on that root page. So from my perspective, the data record has to be allowed to be on pages. 

I looked a little around and found, that Powermail, GridElements, and news extension are doing this in _ext_localconf.php_ calling `ExtensionManagementUtility::allowTableOnStandardPages()`.

So in this case, it could be a fix putting this line `\TYPO3\CMS\Core\Utility\ExtensionManagementUtility::allowTableOnStandardPages('tx_metaseo_setting_root');` to the _ext_tables.php_ of metaseo. I will try out this later.

**Comment by thomaszbz** [comment]
>  As far as I can tell, the record is placed using the "Control Center" module in the SEO section.

Yes. Which would mean that your workaround should also be available to ordinary users, without tweaking TCA settings.

Your solution might be suitable. I'll have to reproduce the whole issue first. We need to consider that the user unintentionally has more "metaseo roots" after the copy operation. We'll have to figure out if this could have really bad implications. But I think it is shown in the Sitemap section, so the user gets notified somehow and can fix it via SEO tab in case it was unintentional. The other way round: It could also be intentional ;-)

If you're willing to try out your solution and provide a valid patch in the meantime, I'd review and merge it.

Please add yourself into metaseo's "Thanks" section. Thanks.

**Comment by timwehrmann** [comment]
> We need to consider that the user unintentionally has more "metaseo roots" after the copy operation.
Didnt think about this, you might be right with this.

**Comment by thomaszbz** [comment]
It was just a thought. I'd rather say that we can risk this as long as the user can correct additional metaseo roots in the metaseo tab. Should be easy to do. Better than unexpected errors thrown by TYPO3. Which, on-top, are hard to track down. That's at least a bug which needs to be fixed (I still did not try to reproduce it yet).

**Comment by thomaszbz** [comment]
reproduced against f727717cc7816db95d09c105085164cde177cadd (metaseo 2.0.1 develop), TYPO3 7.6.9, PHP 5.6. I also checked that it is really a record of metaseo and not from another extension (with some debug code):

    Attempt to insert record on a page that can't store record of type tx_metaseo_setting_root.
    #0 /var/webadmin/typo3_src/typo3/sysext/core/Classes/DataHandling/DataHandler.php(3646): TYPO3\CMS\Core\DataHandling\DataHandler->copyRecord('tx_metaseo_sett...', '2', 11) 
    #1 /var/webadmin/typo3_src/typo3/sysext/core/Classes/DataHandling/DataHandler.php(3559): TYPO3\CMS\Core\DataHandling\DataHandler->copySpecificPage(2, 5, Array, 1) 
    #2 /var/webadmin/typo3_src/typo3/sysext/core/Classes/DataHandling/DataHandler.php(3318): TYPO3\CMS\Core\DataHandling\DataHandler->copyPages(2, '5') 
    #3 /var/webadmin/typo3_src/typo3/sysext/backend/Classes/Tree/Pagetree/Commands.php(212): TYPO3\CMS\Core\DataHandling\DataHandler->process_cmdmap() 
    #4 /var/webadmin/typo3_src/typo3/sysext/backend/Classes/Tree/Pagetree/Commands.php(135): TYPO3\CMS\Backend\Tree\Pagetree\Commands::processTceCmdAndDataMap(Array) 
    #5 /var/webadmin/typo3_src/typo3/sysext/backend/Classes/Tree/Pagetree/ExtdirectTreeCommands.php(237): TYPO3\CMS\Backend\Tree\Pagetree\Commands::copyNode(Object(TYPO3\CMS\Backend\Tree\Pagetree\PagetreeNode), '5') 
    #6 [internal function]: TYPO3\CMS\Backend\Tree\Pagetree\ExtdirectTreeCommands->copyNodeToFirstChildOfDestination(Object(stdClass), '5') 
    #7 /var/webadmin/typo3_src/typo3/sysext/core/Classes/ExtDirect/ExtDirectRouter.php(139): call_user_func_array(Array, Array) 
    #8 /var/webadmin/typo3_src/typo3/sysext/core/Classes/ExtDirect/ExtDirectRouter.php(87): TYPO3\CMS\Core\ExtDirect\ExtDirectRouter->processRpc(Object(stdClass), 'TYPO3.Component...') 
    #9 [internal function]: TYPO3\CMS\Core\ExtDirect\ExtDirectRouter->routeAction(Object(TYPO3\CMS\Core\Http\ServerRequest), Object(TYPO3\CMS\Core\Http\Response)) 
    #10 /var/webadmin/typo3_src/typo3/sysext/backend/Classes/Http/RouteDispatcher.php(54): call_user_func_array(Array, Array) 
    #11 /var/webadmin/typo3_src/typo3/sysext/backend/Classes/Http/AjaxRequestHandler.php(171): TYPO3\CMS\Backend\Http\RouteDispatcher->dispatch(Object(TYPO3\CMS\Core\Http\ServerRequest), Object(TYPO3\CMS\Core\Http\Response)) 
    #12 /var/webadmin/typo3_src/typo3/sysext/backend/Classes/Http/AjaxRequestHandler.php(89): TYPO3\CMS\Backend\Http\AjaxRequestHandler->dispatch(Object(TYPO3\CMS\Core\Http\ServerRequest)) 
    #13 /var/webadmin/typo3_src/typo3/sysext/core/Classes/Core/Bootstrap.php(302): TYPO3\CMS\Backend\Http\AjaxRequestHandler->handleRequest(Object(TYPO3\CMS\Core\Http\ServerRequest)) 
    #14 /var/webadmin/typo3_src/typo3/sysext/backend/Classes/Http/Application.php(94): TYPO3\CMS\Core\Core\Bootstrap->handleRequest(Object(TYPO3\CMS\Core\Http\ServerRequest)) 
    #15 /var/webadmin/typo3_src/typo3/index.php(20): TYPO3\CMS\Backend\Http\Application->run() 
    #16 [internal function]: {closure}()     #17 /var/webadmin/typo3_src/typo3/index.php(21): call_user_func(Object(Closure))     #18 {main}

**Comment by thomaszbz** [comment]
80f3152 mitigates the error. The metaseo_settings_root record is copied. I applied the fix you proposed. Thanks for pointing this out.

@timwehrmann I'd be happy if you could report back if the problem is solved. I did not test a lot if the patch has further implications. At least the error message is gone, hopefully.

**Comment by bitmotion** [comment]
I will try it out and give feedback as soon as I got some free time _(probably in todays afternoon)_. :-)

**Comment by thomaszbz** [comment]
I filed an issue against TYPO3 core for the logged messages: https://forge.typo3.org/issues/76885

**Comment by timwehrmann** [comment]
The error message does not pop up any more when copying a page with a _tx_metaseo_setting_root_ record on it with 80f3152. Nice, thank you very much. 👍 :-)

**Comment by thomaszbz** [comment]
Thanks for reporting back.

Thanks to a patch provided by Benni Mack, error logging in TYPO3 CMS now improved a lot by naming the affected table and thereby disclosing the "guilty" extension. In addition, logging of the operation is not misleading any more.

The fix also got backported to 7.6 branch and will be published with the next release, presumably 7.6.11.

https://forge.typo3.org/issues/76885
https://forge.typo3.org/issues/76885

**Comment by Domtaholic** [comment]
Don´t know if im doing something wrong but this error happend to me in an Typo3 8.7.17 again.

Deleting the metaseo_settings_root isn´t an option at all, cause this Data holds important settings for every root.

I included the fix 

`\TYPO3\CMS\Core\Utility\ExtensionManagementUtility::allowTableOnStandardPages('tx_metaseo_setting_root');`

You guys are sure the fix is Live?
