### ISSUE TITLE
Scheduler - Error during run Sitemap.txt builder (metaseo)

### ISSUE THREAD

**Issue by albert-spangler** [mblaschke/TYPO3-metaseo#255]
TYPO3 Version: 7.6.6 and 7.6.9
MetaSEO Version: 2.0.0

If I run the scheduler task I get an error:

_Execution of task "Sitemap.txt builder (metaseo)" failed with the following message: PHP Warning: Invalid argument supplied for foreach() in /var/www/.../typo3conf/ext/metaseo/Classes/Sitemap/Generator/TxtGenerator.php line 66_

It seems that in the AbstractGenerator.php in line 118  _$list = SitemapUtility::getList($this->rootPid, $sysLanguageId);_ returns NULL ... but it should be an array.

If I run the task I can see in my debug file that the scheduler job only takes root pid 1 (I installed a workaround for the error above). There are 3 root pages in my test system. So I think the script should run through all 3 pages. Maybe there is another problem too.

**Comment by albert-spangler** [comment]
The frontend language is default so in the tx_metaseo_sitemap table page_language is 0.

The MySQL statement which is generated in SitemapUtility::getList($this->rootPid, $sysLanguageId) looks like: 

SELECT ts.*
                    FROM tx_metaseo_sitemap ts
                            INNER JOIN pages p
                              ON    p.uid = ts.page_uid
                                AND p.deleted = 0
                                AND p.hidden = 0
                                AND p.tx_metaseo_is_exclude = 0
                                AND p.doktype NOT IN ('6','199','254','255')
                   WHERE ts.page_rootpid = **_1_**
                     AND ts.is_blacklisted = 0 AND ts.page_language = 1 ORDER BY
                        ts.page_depth ASC,
                        p.pid ASC,
                        p.sorting ASC;

So it can't get any result.

**Comment by thomaszbz** [comment]
... which means that `$languageId` is set while function `getList($rootPid, $languageId)` is called. That must have happened in `AbstractGenerator` line 113:

    $sysLanguageId = GeneralUtility::getLanguageId();

**Comment by thomaszbz** [comment]
The SQL statement you provided has a condition

    AND ts.page_language = 1

... which means that `$languageId` is set while function `getList($rootPid, $languageId)` is called. That must have happened in `AbstractGenerator` line 113:

    $sysLanguageId = GeneralUtility::getLanguageId();

That function defaults to `0`:

    public static function getLanguageId()
    {
        $ret = 0;

        if (!empty($GLOBALS['TSFE']->tmpl->setup['config.']['sys_language_uid'])) {
            $ret = (int)$GLOBALS['TSFE']->tmpl->setup['config.']['sys_language_uid'];
        }

        return $ret;
    }

Please check your TYPO3 config for `config.sys_language_uid`. When set to `0`, you should get a result. Otherwise not.

In case you willingly want to go for `config.sys_language_uid=1`, you might have to change values in ` tx_metaseo_sitemap.page_language` accordingly.

Please report back if that fixes the issue.

**Comment by albert-spangler** [comment]
Ok. I changed my root-template.ts 
    sys_language_uid = 0
into
    sys_language_uid = 1
I deleted all records in BE -> Sitemap -> Sitemaps. After revisit the sites all new records in the database have now have page_language = 1 and the return of $list['tx_metaseo_sitemap'] in an array.

config.sys_language_uid = 0 still returns an error

But ...

I have 5 website languages on my very first root page (id = 0). If I run the scheduler job all 5 languages are checked by the extension. There are no records in other languages then page_language = 1 on page_rootid = 1 so the scheduler returns 

Execution of task "Sitemap.txt builder (metaseo)" failed with the following message: PHP Warning: Invalid argument supplied for foreach() in /var/www/..../typo3conf/ext/metaseo/Classes/Sitemap/Generator/TxtGenerator.php line 66

by check on language id = 2,3,...

So I think thats why the scheduler aborted with an error ...

**Comment by thomaszbz** [comment]
What does the SQL look like and what's the result of it now?

**Comment by thomaszbz** [comment]
aee8da8 is for the handling of an empty sitemap only. So it gets rid of the runtime error and outputs an empty site map accordingly. Tested with 7.6.10.

Is your sitemap still empty?

**Comment by thomaszbz** [comment]
In principle, language iteration is working with 2.0.0.

For a sitemap, I get

https://example.com/index.php?id=4
https://example.com/index.php?id=4&L=1
https://example.com/index.php?id=4&L=2
