### ISSUE TITLE
Privacy-aware GA tracking code

### ISSUE THREAD

**Issue by thomaszbz** [mblaschke/TYPO3-metaseo#266]
@c2po reported via PR #265:

> It seems to be very important that configuration of analytics (in particular **ga('set', 'anonymizeIp', true)**) is set before **ga('send', 'pageview')** is performed.

https://www.datenschutzbeauftragter-info.de/fachbeitraege/google-analytics-datenschutzkonform-einsetzen/
https://developers.google.com/analytics/devguides/collection/analyticsjs/ip-anonymization
https://support.google.com/analytics/answer/2763052?hl=en

**Comment by thomaszbz** [comment]
All versions of metaseo are affected by this issue: https://github.com/c2po/TYPO3-metaseo/blame/1.0.0/Resources/Private/Templates/PageParts/ServiceGoogleAnalytics.html#L23

@c2po Thanks for your contribution. Trying to be privacy-aware, I'm not using GA myself, therefore can't test this against a real GA account. Your patch looks valid (according to the examples), but have you been testing it? If yes, I'd go for a merge.

**Comment by c2po** [comment]
I tested the change of the order with a real GA account and it worked as expected BUT I do not use gaCustomizationCode. My PR #265 could be be a breaking change for users of gaCustomizationCode. That is why I will delete PR #265.

(Explanation: anbody using gaCustomizationCode must send a pageview again, because it has been sent before the code execution of gaCustomizationCode. With my change anonymizeIp is again not executed before gaCustomizationCode...)

Is anybody using this feature? Setting anonymizeIp multiple times could solve this without breaking.

**Comment by thomaszbz** [comment]
I think it would be great to encourage people to use the anonymizeIp feature (while I still have to do my homework and look up if it actually has an effect in respect to avoiding a http request against google server initiated on client side, which would expose the client's IP to google no matter what configuration says). That said, this issue is anyways a bug against metaseo's feature set. Which must be fixed, respectively.

Are you sure that your patch is not valid? It looked similar to google's examples.

If you can provide a patch of which you think it could be suitable, I'd be happy to review and merge it. Please don't forget to add yourself (or your pseudonym) to the list of contributors.

**Comment by c2po** [comment]
I is valid if you do not use any customization code.
And it is valid if the customization code user is responsible him-/herself for setting anonymizeIp.

I will provide a patch if a customization user acknowleges that following pseudocode will not break his/her customization code:
```
if (gaCustomizationCode) {
  if (gaIsAnonymize) ga('set', 'anonymizeIp', true);
  more customization code here;
}
if (gaIsAnonymize) ga('set', 'anonymizeIp', true);
ga('send', 'pageview');
```

Explanation:
Set anoymizeIp before gaCustomizationCode to anonymize contacts to the collection network. And set anoymizeIp after to make sure it is still set after gaCustomizationCode.

> Still, some say that this anonymization is not really sufficient as the IP address   is anonymized only after it has already reached google's servers. So Google still gets your IP address even if you use IP anonymization. This is not evilness of google, it is simply not possible otherwise technically.
[quora](https://www.quora.com/What-are-the-consequenses-of-using-IP-Anonymization-in-Google-Analytics-from-a-digital-marketing-point-of-view)

**Comment by thomaszbz** [comment]
Fine, the cite you provide also solves my homework (=> a useless feature if google was evil). However, we should still fix this bug in the hope that the guys at google respect their own feature.

I'd merge your patch for all cases you mentioned. Metaseo 2.0.1 got released a few days ago, which leaves everybody enough time to test the change in the develop branch before we release it (as well as after the release). After all, in case `gaCustomizationCode` is rarely used, there is no risk to break many production systems, so the risk is very limited.

As far as I can see, the change you proposed even looks non-breaking for folks that use the `gaCustomizationCode` feature. Even if it should break something, by the nature of the feature, folks should know what they customize and be ready to take care upon their changes.
