### ISSUE TITLE
cHash: Check for side effects of security fix typo3-core-sa-2016-022

### ISSUE THREAD

**Issue by thomaszbz** [mblaschke/TYPO3-metaseo#268]
TYPO3 6.2.27 and 7.6.11 introduce changes to cHashes in respect to caching.

It looks like the new behaviour (which also fixes the security issue) must be activated _manually_ on existing pre-7.6.11 installations with a newly introduced configuration variable.

```
$GLOBALS['TYPO3_CONF_VARS']['FE']['cHashIncludePageId'] = true;
```

![cHashIncludePageId](https://cloud.githubusercontent.com/assets/11200727/18475804/24d3d8c8-79c8-11e6-8e5b-80ab175410bb.png)

That said, side effects should not occur on existing pages without manual intervention.

If someone encounters side effects (no matter if good or bad) after applying the patch, please report back in this issue. The change in behaviour could be bad (because we use that cHashy caching a lot). But it could also be good, as it potentially mitigates duplicate (cache) and weird entries we were faced with from time to time.

A side effect could also be that the patch invalidates metaseo's sitemap or disables metaseo's caching strategies to do the indexing stuff. This is a reminder for the change in TYPO3 in case someone comes up with a problem.

Interim workaround for problems after application: Try to undo the change in configuration. However, this exposes your installation to the security isse with the risk of beeing DOSed again. Therefore, this is just an interim workaround if your site goes down (which is as bad as being DOSed), or similar.

References:
- https://typo3.org/teams/security/security-bulletins/typo3-core/typo3-core-sa-2016-022/
- https://github.com/TYPO3/TYPO3.CMS/commit/8aecd0c1f8654a6068b63c6ab76ea9a7f42a4205

**Comment by thomaszbz** [comment]
TODO:

### Test with metaseo 2.0.0, TYPO3 6.2.26 and just sources updated to 6.2.27

- [ ] Site reachable
- [ ] Site reachable after cleared cache
- [ ] Sitemap reachable after cleared cache

### Test with metaseo 2.0.0, TYPO3 6.2.26 and sources updated to 6.2.27 _and_ `cHashIncludePageId` set to `true`

- [ ] Site reachable
- [ ] Site reachable after cleared cache
- [ ] Sitemap reachable after cleared cache

**Comment by hdi-kw** [comment]
So far I see only improvements after setting cHashIncludePageId =1 in TYPO3 7.6.11 with realurl, tx_news and multi language. Before the metaseo sitemap had over 7000 entries with a lot of garbage. Now the sitemap contains around 450 entries and looks much better.

**Comment by thomaszbz** [comment]
TYPO3 CMS 6.2.28/7.6.12 come up with additional fixes in respect to cHashes:

> 2016-10-12  59f7404  #78021          [BUGFIX] Exception with cHashIncludePageId but no id in the URL (Dmitry Dulepov)
> 2016-09-30  0aa80a6  #78102          [BUGFIX] Incorrect cHash generation may cause 404 on any page (Dmitry Dulepov)

References:
https://wiki.typo3.org/TYPO3_CMS_6.2.28
https://wiki.typo3.org/TYPO3_CMS_7.6.12

**Comment by thomaszbz** [comment]
Only got positive feedback so far. Which is great as there's nothing to do. Closing this issue now.

If you find problems related to this RFC, please feel free to open a new issue and reference to #268.
