### ISSUE TITLE
PHP Warnings

### ISSUE THREAD

**Issue by mblaschke** [mblaschke/TYPO3-metaseo#29]
Core: Error handler (FE): PHP Warning: Invalid argument supplied for foreach() in /.../html/typo3/typo3conf/ext/metaseo/Classes/Utility/GeneralUtility.php line 178    
Core: Error handler (FE): PHP Warning: array_reverse() expects parameter 1 to be array, null given in /.../html/typo3/typo3conf/ext/metaseo/Classes/Utility/GeneralUtility.php line 176    
Core: Error handler (FE): PHP Warning: ksort() expects parameter 1 to be array, null given in /.../html/typo3/typo3conf/ext/metaseo/Classes/Utility/GeneralUtility.php line 173    
Core: Error handler (FE): PHP Warning: Invalid argument supplied for foreach() in /.../html/typo3/typo3conf/ext/metaseo/Classes/Utility/GeneralUtility.php line 178

**Comment by thomaszbz** [comment]
Same applies for current 2.0.0 development branch:

    Core: Error handler (FE): PHP Warning: Invalid argument supplied for foreach() in /var/www/.../typo3conf/ext/metaseo/Classes/Utility/GeneralUtility.php line 403

Flushing system caches did not help here.

**Comment by mblaschke** [comment]
Hopefully fixed in master (d524d63)
Hopefully fixed in develop (17de5f3)
