### ISSUE TITLE
Description übersetzung erscheint nicht im Frontend

### ISSUE THREAD

**Issue by glucka** [mblaschke/TYPO3-metaseo#3]
Die description Meta Tags werden immer in der default sprache gezeigt im Fronend.

**Comment by tiwden** [comment]
Wir haben hier das gleiche Problem, Description und Keywords werden immer aus der default Sprache gezogen. Das problem scheint zu sein das $GLOBALS['TSFE']->cObj nicht den page_language_overlay benutzt. Welche Extension hat den vorher diese Problem verursacht? Jemand Vieleicht eine Idee warum das cObj nicht mit den Overlay Daten gefüllt wird? 
Eingesetzt wird Typo3 6.2

**Comment by thomaszbz** [comment]
Was reported to fluidpages: https://github.com/FluidTYPO3/fluidpages/issues/270

**Comment by glucka** [comment]
Für mich war die einfachste Lösung folgende Code in meine Page Template:
´´´
<v:page.header.meta name="keywords" content="{v:page.info(field:'keywords')}}"/>
<v:page.header.meta name="description" content="{v:page.info(field:'description')}"/>
´´´

**Comment by thomaszbz** [comment]
Classified as bug, as we can reproduce it (via #122), although we still don't know the reason for it. Fluidpages project does not feel responsible, so it could still be a bug in the core or in metaseo.
