### ISSUE TITLE
piwik: mixed content in <noscript>

### ISSUE THREAD

**Issue by thomaszbz** [mblaschke/TYPO3-metaseo#30]
On a https-secured page, a non-secured counter pixel is used in the tracking code for users that have no javascript-support:

    <noscript><p><img src="http://example.com/piwik.php?idsite=1" style="border:0" alt="" /></p></noscript>

Piwik 2.12.0 uses

    <noscript><p><img src="//example.com/piwik.php?idsite=1" style="border:0;" alt="" /></p></noscript>

which uses https on secured pages.

**Comment by mblaschke** [comment]
Fixed in develop (312753b)
Fixed in master (00673cd)
