### ISSUE TITLE
7.6 LTS: TCA: Reference to "wizard_element_browser" was migrated to new "wizard_link"

### ISSUE THREAD

**Issue by thomaszbz** [mblaschke/TYPO3-metaseo#325]
According to documentation, wizard_link is documented in v7.6+, but not yet in 6.2.

v8-dev: https://docs.typo3.org/typo3cms/TCAReference/AdditionalFeatures/CoreWizardScripts/Index.html
v7.6-lts: https://docs.typo3.org/typo3cms/TCAReference/7.6/AdditionalFeatures/CoreWizardScripts/
v6.2-lts: https://docs.typo3.org/typo3cms/TCAReference/6.2/AdditionalFeatures/CoreWizardScripts/

@snduesel provided patches via #322 and #323.

@snduesel I assume this is not running together with TYPO3 6.2 (which we still support). Can you confirm that?

@snduesel I also assume that your patch is not a bugfix but does some refactoring. Is your patch **necessary** for v8-LTS compatibility?

I guess we can merge this after dropping support for 6.2 (which we will do soon).

**Comment by snduesel** [comment]
> @snduesel I assume this is not running together with TYPO3 6.2 (which we still support). Can you confirm that?

I don't know. I have tested only in TYPO3 7.6 #322 #323 #324 

> @snduesel I also assume that your patch is not a bugfix but does some refactoring. Is your patch necessary for v8-LTS compatibility?

#324 is a necessary Bugfix for TYPO3 7.6, but not #322 #323 (It's refactoring for v8)

**Comment by thomaszbz** [comment]
Related: #143 `wizard_element_browser` was introduced for 7.6 compatibility and is still backwards compatible to 6.2 (via 3c9c1137f75a6f9b1673efb0cd6edcb98835a810).

These were the original refactoring steps of #143:
Found the exact refactoring step of 3c9c113:
- https://wiki.typo3.org/Exception/CMS/1437750231
- https://docs.typo3.org/typo3cms/extensions/core/latest/Changelog/7.0/Breaking-59659-DeprecatedCodeRemovalInBackendSysext.html

**Comment by snduesel** [comment]
I get this Message in my TYPO3 7.6 depcation.log:
Reference to "wizard_element_browser" was migrated to new "wizard_link"...

**Comment by thomaszbz** [comment]
@snduesel Great. Deprecation messages need to be mitigated by refactoring the code, of course. But we can do this just as soon as there is a migration path. If I get it right, the migration path requires that we drop support for 6.2 first. Dropping support for 6.2 blocks to merge the patch for the moment.

As far as I know, the existing code does at least run with 7.6 (just that it is deprecated). So this issue is pure refactoring for 7.6.

If `wizard_element_browser` got removed in 8 LTS, then it's a breaking change for 8 LTS. Is that the case?

**Comment by thomaszbz** [comment]
`wizard_element_browser` is deprecated since 6.2 already and gets replaced with `wizard_backend_layout`:

https://github.com/TYPO3/TYPO3.CMS/blob/TYPO3_6-2/typo3/sysext/backend/Classes/Form/FormEngine.php#L4589

That got refactored in 7.6, whereas `wizard_element_browser` still exists: https://github.com/TYPO3/TYPO3.CMS/blob/TYPO3_7-6/typo3/sysext/recordlist/Configuration/Backend/Routes.php

As of 8.5 and current master, that file remains unchanged:
https://github.com/TYPO3/TYPO3.CMS/blob/TYPO3_8-5/typo3/sysext/recordlist/Configuration/Backend/Routes.php

Theoretically, the existing code is still running with 8.5, which renders this issue as pure refactoring, even for 8.5.

**Comment by snduesel** [comment]
Then its pure refactoring ;-)

**Comment by thomaszbz** [comment]
Related: `wizard_backend_layout` has been removed as of TYPO3 8.1:

https://github.com/TYPO3/TYPO3.CMS/blob/master/typo3/sysext/core/Documentation/Changelog/8.1/Breaking-75497-InlineBackendLayoutWizard.rst

So it was wise to not use it ;-)

**Comment by thomaszbz** [comment]
PR #329 replaces PR #322 and #323.

@snduesel Sorry, I could not preserve the original commits because the original PRs got closed and the original branch got deleted. PR #329 is exactly what you suggested, however.

**Comment by thomaszbz** [comment]
In 8.6, `wizard_link` was touched in the core: https://github.com/TYPO3/TYPO3.CMS/blob/ed744d551a5390e906dabba41f4ddd79175cac67/typo3/sysext/core/Documentation/Changelog/8.6/Deprecation-79440-TcaChanges.rst#link-browser

Eventually, we can't use `wizard_link` any more in 8.6. Still needs to be tested.

**Comment by thomaszbz** [comment]
Seems as if that still works in 8.7 LTS:
![auswahl_177](https://cloud.githubusercontent.com/assets/11200727/24837992/1aa60102-1d40-11e7-9c9f-2fb66be00287.png)

**Comment by thomaszbz** [comment]
**MetaSEO version**: 3.0.0-dev
**TYPO3 version**: 8.7.0
**PHP version**: 7.0.16

How to reproduce:

- open install tool
- Configuration Presets: Enable "Debug" mode
- Important Actions: Execute "Check TCA Migrations"

`The icon path of wizard "link" from TCA table "pages['columns']['tx_metaseo_canonicalurl']['config']['wizards']['link']['icon']"has been migrated to pages['columns']['tx_metaseo_canonicalurl']['config']['wizards']['link']['icon']" = 'actions-wizard-link'.

The icon path of wizard "link" from TCA table "pages_language_overlay['columns']['tx_metaseo_canonicalurl']['config']['wizards']['link']['icon']"has been migrated to pages_language_overlay['columns']['tx_metaseo_canonicalurl']['config']['wizards']['link']['icon']" = 'actions-wizard-link'.

Reference to "wizard_element_browser" was migrated from"pages['columns']['tx_metaseo_canonicalurl']['config']['wizards']['link']['module']['name'] === 'wizard_element_browser'"to new "wizard_link", "pages['columns']['tx_metaseo_canonicalurl']['config']['wizards']['link']['module']['name'] = 'wizard_link' "

Reference to "wizard_element_browser" was migrated from"pages_language_overlay['columns']['tx_metaseo_canonicalurl']['config']['wizards']['link']['module']['name'] === 'wizard_element_browser'"to new "wizard_link", "pages_language_overlay['columns']['tx_metaseo_canonicalurl']['config']['wizards']['link']['module']['name'] = 'wizard_link' "`
