### ISSUE TITLE
TYPO3 7.x compatibility

### ISSUE THREAD

**Issue by mblaschke** [mblaschke/TYPO3-metaseo#33]
Check and fix issues

**Comment by mblaschke** [comment]
Fixed issue with 6d29018442f5be4f1b31fbee2770503c5d3c2791
Should be working now

**Comment by prentice87** [comment]
MetaSEO is not showing anything on Typo3 CMS 7.2.0 from 28th April '15. Is there a fix so i can edit the Information? I did delete the cache and so on but nothing shows up.

**Comment by mblaschke** [comment]
Will check this issue in the next days with TYPO3 7.2

**Comment by mblaschke** [comment]
Have you testet 2.0 (Github develop branch)?

**Comment by prentice87** [comment]
I get: Argument "addCssFile" was not registered.
http://wiki.typo3.org/Exception/CMS/1237823695

Would the migration extension from tq_seo to metaseo still work?

**Comment by mblaschke** [comment]
MetaSEO (current develop branch) should be working again :)
