### ISSUE TITLE
Deleted pages_language_overlay used

### ISSUE THREAD

**Issue by glucka** [mblaschke/TYPO3-metaseo#333]
MetaSEO version**: 2.0.3

Wenn eine gelöschte pages_language_overlay row in db vorhanden ist wird immer diese verarbeitet.
Im Frontend erscheint deshalb nicht das richtige Browsertitle weil das richtige (nicht gelöschte) pages_language_overlay row in db wird nie verarbeitet.

**Comment by thomaszbz** [comment]
@glucka 

Habe versucht, es zu reproduzieren (TYPO3 7.6.14, metaseo 2.0.3):

Übersetzung angelegt (wird später gelöscht)

![auswahl_119](https://cloud.githubusercontent.com/assets/11200727/22107561/f7c19564-de4e-11e6-818c-9e2bf7372f7e.png)

Übersetzung gelöscht (ganze Übersetzungs-Seite):

![auswahl_120](https://cloud.githubusercontent.com/assets/11200727/22107587/0d0283de-de4f-11e6-84f2-cc2897473967.png)

Übersetzung nochmal neu angelegt:

![auswahl_121](https://cloud.githubusercontent.com/assets/11200727/22107636/4253a37e-de4f-11e6-9e71-8558ccee1539.png)

Dem Bug report entsprechend, müsste ich jetzt eigentlich `Deutschgeloescht` als Titel angezeigt bekommen, damit der Fehler reproduziert wäre. Wo ist mein Denkfehler? Was muss ich anders machen?

Wie sieht Deine Template-Constants/Setup in Bezug auf metaseo-Titel aus?

**Comment by thomaszbz** [comment]
Es sieht für mich so aus, als ob die gepatchte Funktion nur für Ajax-Requests ausgeführt wird, also nur im TYPO3-Backend (also nicht im TYPO3-Frontend).

Insofern war mein Versuch, das zu reproduzieren obsolet.

Im Backend ist es deutlich entspannter, und die Änderung scheint prinzipiell sinnvoll zu sein, auch wenn ich jetzt keinen Bug reproduzieren kann. Laufen tut's scheinbar noch.

@glucka Vielleicht interessant für Dich: #336 fixt Ajax-Übersetzungen von Seitentiteln im Backend. Kam heute dazu.

**Comment by glucka** [comment]
Genao. Deine test müsstest du nur weiter machen.
Versuche nur in Backend über Das Metaseo plugin das Titel ändern. Geht nicht, wird immer das gelöschte page_language_overlay row verändert!
![screenshot from 2017-01-20 09-54-59](https://cloud.githubusercontent.com/assets/6602365/22143235/9f342e38-def9-11e6-99de-e6460cb69ccf.png)

**Comment by glucka** [comment]
Das betrifft auch die andere Felder. Prefix suffix usw...
Ich mache ein PR
