### ISSUE TITLE
Signal Slots: Missing call by reference in GeneralUtility->callHookAndSignal()

### ISSUE THREAD

**Issue by SicorDev** [mblaschke/TYPO3-metaseo#343]
**MetaSEO version**: 2.0.3
**TYPO3 version**: 7.6.15 
**PHP version**: 5.6.29

Some signals are not working, because of the missing call by reference argument for non-objects.
The function call 
`$signalSlotDispatcher->dispatch($class, $name, array($args, $obj));`

inside \Metaseo\Metaseo\Utility\GeneralUtility->callHookAndSignal() should be `$signalSlotDispatcher->dispatch($class, $name, array(&$args, $obj));`

**Comment by thomaszbz** [comment]
@SicorDev Thanks for catching this. Related:  #264 was supposed to fix this in 2.0.2.

Which hook did you use when you hit this issue?

Can you please reassert that #264 does not fix this? Please clear all caches (including opcode caches in the install tool) and try once again with 2.0.3. It's just to make sure that the bug really is not fixed via #264.

**Comment by thomaszbz** [comment]
Just for the record: TYPO3's signal slot dispatcher does a

    /**
     * Dispatches a signal by calling the registered Slot methods
     *
     * @param string $signalClassName Name of the class containing the signal
     * @param string $signalName Name of the signal
     * @param array $signalArguments arguments passed to the signal method
     * @return mixed
     * @throws Exception\InvalidSlotException if the slot is not valid
     * @throws Exception\InvalidSlotReturnException if a slot returns invalid arguments (too few or return value is not an array)
     * @api
     */
    public function dispatch($signalClassName, $signalName, array $signalArguments = [])
    {
        [...]
        return $signalArguments;
    }

Which in turn means that the function returns the arguments as an array, presumably in the same format as the third parameter of the function.

If possible, we should take the return value of the function. That's what #264 was supposed to do. Eventually, #264 is not fully there yet...

**Comment by thomaszbz** [comment]
Here's some code taken from the backend (`TYPO3\CMS\Backend\Utility\BackendUtility`):

    protected static function emitGetPagesTSconfigPreIncludeSignal(array $TSdataArray, $id, array $rootLine, $returnPartArray)
    {
        $signalArguments = static::getSignalSlotDispatcher()->dispatch(__CLASS__, 'getPagesTSconfigPreInclude', array($TSdataArray, $id, $rootLine, $returnPartArray));
        return $signalArguments[0];
    }

That code uses no `list()` function and no parameter is submitted by reference (whereas I really would like to avoid the latter one).

Can't we do it like that?

**Comment by thomaszbz** [comment]
@SicorDev What happens if you write:

    public static function callHookAndSignal($class, $name, $obj, &$args = null)
    {
    [...]
    $signalArguments = $signalSlotDispatcher->dispatch($class, $name, array($args, $obj));
    $args = $signalArguments[0];
    }

**Comment by SicorDev** [comment]
I cleared all the caches and it's still the same behaviour.
Let's say this is my example implementation: (Signal and ext_tables.php)
<pre>
public function metatagOutput(&$args, $obj) {
        $objectManager = GeneralUtility::makeInstance(ObjectManager::class);
        $pageRepository = $objectManager->get(PageRepository::class);
        $parent = $pageRepository->getPage($GLOBALS['TSFE']->page["uid"]);

        // No description found -> fallback
        if(!$args["meta.description"]["attributes"]["content"]) {
            $args["meta.description"] = array('tag' => 'meta','attributes' => array('name' => 'description', 'content' => $parent["description"]));
        }
}

$signalSlotDispatcher = \TYPO3\CMS\Core\Utility\GeneralUtility::makeInstance(\TYPO3\CMS\Extbase\SignalSlot\Dispatcher::class);
$signalSlotDispatcher->connect(
    \Metaseo\Metaseo\Page\Part\MetatagPart::class,  // Signal class name
    'metatagOutput',                                  // Signal name
    \SICOR\SicMeta\Hooks\MetaFallbackSignal::class,        // Slot class name
    'metatagOutput'                                // Slot name
);
</pre>
The idea behind the Signal Slot concept should be the possibility to edit the passed argument inside your slot. The easiest way is to pass the argument by reference and modifiy it.
If you add the & the example above works as intended. 

Have a look at the powermail signals for example: (Call by reference only for non-objects)
https://docs.typo3.org/typo3cms/extensions/powermail/ForDevelopers/SignalSlots/Index.html

I also tested your last suggestion, but i can't get it to work:
<pre>
public function metatagOutput(&$args, $obj) {
        $objectManager = GeneralUtility::makeInstance(ObjectManager::class);
        $pageRepository = $objectManager->get(PageRepository::class);
        $parent = $pageRepository->getPage($GLOBALS['TSFE']->page["uid"]);

        // No description found -> fallback
        if(!$args["meta.description"]["attributes"]["content"]) {
            $args["meta.description"] = array('tag' => 'meta','attributes' => array('name' => 'description', 'content' => $parent["description"]));
        }
        return $args;
}
</pre>

Why are you so concerned about using a simple call by reference to solve the problem ?

**Comment by thomaszbz** [comment]
564ce37 is invalid because it works around the error handling in https://github.com/TYPO3/TYPO3.CMS/blob/master/typo3/sysext/extbase/Classes/SignalSlot/Dispatcher.php#L150

It is very likely that the error happens somewhere else: Eventually something goes wrong when calling the hook.

**Comment by SicorDev** [comment]
Hm, could you test your fix ?
Im not insisting on my solution, i just need a working one.

**Comment by thomaszbz** [comment]
Please have a look into https://github.com/TYPO3/TYPO3.CMS/blob/master/typo3/sysext/extbase/Classes/SignalSlot/Dispatcher.php#L150

Please note that $params only make it into the return value, if execution does not fail. That should work with the existing code.

I guess in your case something fails when dispatching. For that case the dispatcher does not return changes. Eventually, you worked around that by passing the variable by reference.

But that's not how this function is supposed to be used.

Please try out my 2 lines of code. I can't test it that quick.

Please also check your logs (in TYPO3 development mode). Eventually, you see an `Exception\InvalidSlotReturnException` somewhere.

**Comment by thomaszbz** [comment]
What happens if you do:

    $signalSlotDispatcher->connect(
        \SICOR\SicMeta\Hooks\MetaFallbackSignal::class,        // Slot class name
        'metatagOutput'                                // Slot name
    );

Without connecting Metaseo's metatagOutput?

**Comment by SicorDev** [comment]
Alright i got a working example:
<pre>
    public function metatagOutput($args, $obj) {
        $objectManager = GeneralUtility::makeInstance(ObjectManager::class);
        $pageRepository = $objectManager->get(PageRepository::class);
        $parent = $pageRepository->getPage($GLOBALS['TSFE']->page["uid"]);

        // No description found -> fallback
        if(!$args["meta.description"]["attributes"]["content"]) {
            $args["meta.description"] = array('tag' => 'meta','attributes' => array('name' => 'description', 'content' => $parent["description"]));
        }

        // No keywords found -> fallback
        if(!$args["meta.keywords"]["attributes"]["content"]) {
            $args["meta.keywords"] = array('tag' => 'meta','attributes' => array('name' => 'keywords', 'content' => $parent["keywords"]));
        }
        return array($args, $obj);
    }
</pre>

This works with your provided code above.
Thanks for your help. Should I update my pull request, or would you like to update it yourself ?

**Comment by thomaszbz** [comment]
Does it also work with the `list()` variant, leaving the original v2.0.3 unchanged?

**Comment by thomaszbz** [comment]
@SicorDev Does it also work with the `list()` variant, leaving the original v2.0.3 unchanged?

**Comment by SicorDev** [comment]
Yes it does. Thank you :)
It would be helpful to have a little bit more of a documentation for the signals.
I expected it to work like the powermail implementation, so I got of the track..

**Comment by thomaszbz** [comment]
MetaSEO's signals were brought into existence by @mblaschke . I'm still learning how to deal with them myself ;-)

But yes, documentation should get improved... If you want to help out, I'd be happy to merge your patches (create new issue, please).

**Comment by thomaszbz** [comment]
@SicorDev Btw: Your way to call the hook/signal could be great as an example for documentation. If you want to add it for demonstration (how to use the hook/signal thing), please file an issue and PR.

**Comment by phpweb** [comment]
Hello @SicorDev, please tell us how you solved the problem? 

I have the same problem and I have tried this

`
$signalSlotDispatcher->connect(

    \Metaseo\Metaseo\Page\Part\MetatagPart::class,  // Signal class name

    'metatagOutput',                                  // Signal name

    \Triplesense\TsUtilities\Hooks\Metatag::class,// Slot class name

    'metatagOutput' // Slot name

);
`

and this:

`$signalSlotDispatcher->connect(
\Triplesense\TsUtilities\Hooks\Metatag::class,// Slot class name
'metatagOutput' // Slot name
);`

but no success. I can not change the value of **$args**.

It is defintely directed to the custom hook but it does not change the value of **$args**.

Thanks in advance,

**Comment by SicorDev** [comment]
Hello @phpweb 

I'm connecting my SignalSlot like this:
```php
$signalSlotDispatcher = \TYPO3\CMS\Core\Utility\GeneralUtility::makeInstance(\TYPO3\CMS\Extbase\SignalSlot\Dispatcher::class);
$signalSlotDispatcher->connect(
    \Metaseo\Metaseo\Page\Part\MetatagPart::class,  // Signal class name
    'metatagOutput',                                  // Signal name
    \SICOR\SicMeta\Hooks\MetaFallbackSignal::class,        // Slot class name
    'metatagOutput'                                // Slot name
);
```

My Class looks like this: (the important parts)
```php
<?php
namespace SICOR\SicMeta\Hooks;

use TYPO3\CMS\Core\SingletonInterface;
use TYPO3\CMS\Core\Utility\GeneralUtility;
use TYPO3\CMS\Extbase\Object\ObjectManager;
use TYPO3\CMS\Extbase\Reflection\ObjectAccess;
use TYPO3\CMS\Frontend\Page\PageRepository;

class MetaFallbackSignal implements SingletonInterface
{
    /**
     * Metaseo Signal for page metadata
     * see -> \Metaseo\Metaseo\Page\Part\MetatagPart->processMetaTags
     *
     * @param $args
     * @param $obj
     * @return array
     */
    public function metatagOutput($args, $obj) {
            if (!$args["meta.description"]["attributes"]["content"]) {
                $args["meta.description"] = array('tag' => 'meta', 'attributes' => array('name' => 'description', 'content' => $parent["description"]));
            }

            return array($args, $obj);
        }
    }
}

```

**Comment by phpweb** [comment]
wow @SicorDev du bist der Hammer. Thank you very much. It works, I confirm it.
