### ISSUE TITLE
Connector.php setPageTitle() checks GLOBAL[TSFE] instead of GLOBALS[TSFE]

### ISSUE THREAD

**Issue by topfender** [mblaschke/TYPO3-metaseo#347]
**MetaSEO version**: 2.0.3
**TYPO3 version**: 7.6.15
**PHP version**: 5.6.21

I wonder if this is on purpose or if it is an actual bug. I tried to change the pagetitle with the `Connector` class. But `setPageTitle()` doesn't do anything. 
`if ($updateTsfe && !empty($GLOBAL['TSFE']))` always returns false , because `$GLOBAL['TSFE']` doesn't exist.

**Comment by thomaszbz** [comment]
@topfender Thanks for catching this. Looks like a typo. Could you please test my patch and report back what it does to it? I did not test it myself yet.

**Comment by topfender** [comment]
@thomaszbz it works fine, thanks.

**Comment by thomaszbz** [comment]
Thanks for reporting back.

Issue will be closed on merge, automagically.
