### ISSUE TITLE
The SEO Icon in the navigation should be black/white

### ISSUE THREAD

**Issue by simonschaufi** [mblaschke/TYPO3-metaseo#359]
**MetaSEO version**: 2.0.3

**TYPO3 version**: 7.6.16

To be compatible with the overall layout of the backend, the SEO icon (to open and collapse the sub navigation) should be black/white.

**Comment by thomaszbz** [comment]
Contributor added a TYPO3 version detection to work around being blocked by 6 LTS.

**Comment by thomaszbz** [comment]
PR #367 is valid against 7.6:

Before:
![auswahl_165](https://cloud.githubusercontent.com/assets/11200727/24762081/934c87d4-1aed-11e7-9195-8b5adb51eef1.png)

After applying the patch:
![auswahl_166](https://cloud.githubusercontent.com/assets/11200727/24762100/a0112678-1aed-11e7-88ac-a3dcf5320045.png)

Currently testing against 6.2. Hold on...

**Comment by thomaszbz** [comment]
Via PR #368:

- rebased patch set
- applied PSR-2 coding style
- removed `:class` for 5.3 compat
- added name

@simonschaufi Do you go along with PR #368?
