### ISSUE TITLE
LTS8 Call to undefined method after clicking edit icon of rootpage inside control center module

### ISSUE THREAD

**Issue by mediaessenz** [mblaschke/TYPO3-metaseo#378]
LTS8: `Call to undefined method TYPO3\CMS\Core\Page\PageRenderer::setBackPath()` after clicking edit icon of rootpage inside control center module

**Comment by thomaszbz** [comment]
Related: https://forge.typo3.org/projects/extension-cal/repository/revisions/6284f7cae540a186a4821f18590ffb430a936604/diff/Classes/Controller/Api.php

**Comment by thomaszbz** [comment]
The patch removes the workaround #150, which was necessary because of a regression in 7.4. Hope they fixed that otherwise. Needs to be tested. Anyways: The old workaround can't be applied any more in 8LTS. Had to remove it completely, because the function it uses does not exist any more.
