### ISSUE TITLE
Refactoring: use functions in class MetatagPart

### ISSUE THREAD

**Issue by thomaszbz** [mblaschke/TYPO3-metaseo#39]
There's a bunch of statements of the kind

    ... = '<meta name="{name}" content="' . htmlspecialchars({content}) . '">';

and similar statements in class MetatagPart.

A function could be used for that leading to more maintainable code.

#38 needs to be merged before further refactorings make sense.

**Comment by mblaschke** [comment]
Maybe we can use typoscript and could be customizeable with CASE object

**Comment by mblaschke** [comment]
I'm trying to use a CASE renderer but this could slow down MetaSEO a little bit... :(

**Comment by mblaschke** [comment]
Alternative: TagRenderer as function/class with paramters:
$tagRenderer->render($tag, $attributes);

Would be not so nice as CASE but faster :)
