### ISSUE TITLE
8LTS: Control Center: Icons broken

### ISSUE THREAD

**Issue by thomaszbz** [mblaschke/TYPO3-metaseo#390]
**MetaSEO version**: 3.0.0-dev
**TYPO3 version**: 8.7.0
**PHP version**: 7.0.16

How to reproduce:

In 8.7.0:
![auswahl_178](https://cloud.githubusercontent.com/assets/11200727/24838297/b5c4c272-1d45-11e7-8f04-6037a3393eeb.png)

In 6.2.x it was more like
![auswahl_179](https://cloud.githubusercontent.com/assets/11200727/24838302/fb5ea118-1d45-11e7-8b5e-6439b80693bf.png)

**Comment by thomaszbz** [comment]
In 6.2, the pencil got rendered to HTML like this: 

<span title="" class="t3-icon t3-icon-actions t3-icon-actions-document t3-icon-document-open" onclick="...;edit[tx_metaseo_setting_root][1]=edit';..."/span>

Which, for the ControlCenter, is defined in a template:
https://github.com/mblaschke/TYPO3-metaseo/blob/develop/Resources/Private/Templates/BackendControlCenter/Main.html#L43

There's another occurence for the BackendRootSettings, which presumably can be fixed similarly:

https://github.com/mblaschke/TYPO3-metaseo/blob/develop/Resources/Private/Templates/BackendRootSettings/Main.html#L93

**Comment by thomaszbz** [comment]
The code

```
    <span title="" class="t3-icon t3-icon-actions t3-icon-actions-document t3-icon-document-open"
        onclick="{RootPage.settingsLink}">&nbsp;</span>
```
can be refactored to 

```
    <f:link.action onclick="{RootPage.settingsLink}">
        <core:icon identifier="actions-document-open" size="small" />
    </f:link.action>
```
Clicking the link even works as expected. However, TYPO3-Styling is applied:
![auswahl_180](https://cloud.githubusercontent.com/assets/11200727/24838660/8f052602-1d4c-11e7-8a49-3ab3a444137d.png)


@mblaschke Is that ok for you if we use TYPO3's icon set?

@mblaschke @mediaessenz Do you have a better idea how to refactor this? We use that pattern over and over... nobody wants to do that twice.

**Comment by mediaessenz** [comment]
For me this is absolute ok.
Just pushed a fix for this to my 361-vue-js-port branch
