### ISSUE TITLE
8LTS: Use Fluid based 'ModuleTemplate'  instead of the rusty 'DocumentTemplate'

### ISSUE THREAD

**Issue by mediaessenz** [mblaschke/TYPO3-metaseo#391]
Modules use old typo3 css classes and ids.
E.g. module headers nav bar has different height than other backend modules.

**Comment by thomaszbz** [comment]
Related:

- Available since February 2015 via https://github.com/lolli42/TYPO3.CMS-Catharsis/commit/cf26e30e58b4f109e43ee75158f855ac1167778a
