### ISSUE TITLE
8LTS: Change icons of backend modules to svg

### ISSUE THREAD

**Issue by mediaessenz** [mblaschke/TYPO3-metaseo#407]

**Comment by thomaszbz** [comment]
Icons look blurrish as of 8.7:

![auswahl_206](https://cloud.githubusercontent.com/assets/11200727/24984541/58435c0c-1fee-11e7-98cb-a76445e2f8de.png)

This is how it looked like in 7.6:
![jcgt5kpsjt](https://cloud.githubusercontent.com/assets/11200727/24984557/6ef1878a-1fee-11e7-9aed-d6700c42a3c0.png)
