### ISSUE TITLE
8LTS: Icon to Ajax-Spinner is broken

### ISSUE THREAD

**Issue by mediaessenz** [mblaschke/TYPO3-metaseo#409]
The icon big-f0f0f0.gif spinner icon is not available anymore since 8.7.0.

**Comment by thomaszbz** [comment]
reproduced.
![auswahl_200](https://cloud.githubusercontent.com/assets/11200727/24909414/0ead1da6-1ec4-11e7-9f9b-15ec7ea253ef.png)
