### ISSUE TITLE
8LTS: little CSS issue

### ISSUE THREAD

**Issue by thomaszbz** [mblaschke/TYPO3-metaseo#412]
**MetaSEO version**: 3.0.0-dev
**TYPO3 version**: 8.7.0
**PHP version**: 7.0.16
**Browser**: FF 52.0.2 (64bit, ubuntu 16.04)

How to reproduce:
![auswahl_203](https://cloud.githubusercontent.com/assets/11200727/24920512/ca995b56-1ee7-11e7-90f0-8ec1ed793dcd.png)

**Comment by mediaessenz** [comment]
Can not reproduce this problem. Nether under chrome 57 nor under firefox 52 (Mac)

**Comment by thomaszbz** [comment]
With e04875f applied, the same browser now shows it perfectly.
![grafik](https://cloud.githubusercontent.com/assets/11200727/25067555/d8d9152c-2247-11e7-8ab3-e28779363eed.png)

**Comment by thomaszbz** [comment]
5c3db8c extends the copied class directly.
