### ISSUE TITLE
8TLS: Awesome Font: Icon not working any more

### ISSUE THREAD

**Issue by thomaszbz** [mblaschke/TYPO3-metaseo#415]
**MetaSEO version**: 3.0.0-dev
**TYPO3 version**: 8.7.0
**PHP version**: 7.0.16

Lately introduced (#359 / 2.0.4) icon using Awesome font is broken already in 8 LTS.

Here's how it looks like in 3.0.0-dev / 8 LTS with patch f73b32744e56fbf432ecf2cf21dc0ba11e9b6b79 applied:

![auswahl_206](https://cloud.githubusercontent.com/assets/11200727/24981559/8efffd60-1fdd-11e7-9e76-ad12afc39415.png)

That's pretty much the same as in metaseo 2.0.3, together with TYPO3 7.6.

Here's how it looked like in 2.0.4/7.6 LTS with patch f73b32744e56fbf432ecf2cf21dc0ba11e9b6b79 applied:

![jcgt5kpsjt](https://cloud.githubusercontent.com/assets/11200727/24981829/c28cca04-1fde-11e7-827c-894178d8ef9b.png)

@simonschaufi If you are willing to patch this again, please check out branch `feature/8lts` and a TYPO3 CMS 8.7.x of your choice.

Related: #359, #408, #407

**Comment by simonschaufi** [comment]
I figured out the problem. It's about iconIdentifier and icon. In v7 iconIdentifier is stronger than icon, in v8 it was turned around. Therefor I need to "unset" the icon.

**Comment by thomaszbz** [comment]
Doing so won't break 7, now that 3.0.0 is for 8 LTS only.

**Comment by thomaszbz** [comment]
Thanks!
