### ISSUE TITLE
Core: Error handler (FE): PHP Warning

### ISSUE THREAD

**Issue by kurtvanc** [mblaschke/TYPO3-metaseo#47]
When I install metaseo at a "usually" working- typo3 installation, then I get the following prompts at the log. They appear about every 10-20 minutes. 

![bildschirmfoto 2015-04-22 um 08 32 20](https://cloud.githubusercontent.com/assets/12062932/7268580/3d8fd2a2-e8cb-11e4-848f-3d31dd0eb988.png)

Any idea how to handle the huge amount on rows at the log?
I can't clear the whole table, because I need the other logs for my customers and the memory is filled up with logs.

**Comment by mblaschke** [comment]
Which version?

**Comment by kurtvanc** [comment]
Die Version lautet 1.0.6

LG Philipp

**Comment by mblaschke** [comment]
Ich schau mir das heute Abend an, sollte eigentlich schon behoben sein.

Kannst du prüfen, ob das mit MetaSEO 2.0 auch auftritt (die Version aus dem develop-branch)?

**Comment by mblaschke** [comment]
Ist, wenn ich richtig sehe, schon für 1.0.7 behoben.

**Comment by kurtvanc** [comment]
Die Frage ist nur, wie man das Ding dann bislang als stable betrieben hat, wenn einem das Logfile jeden 2. Tag so übergeht, dass es die Tables sprengt!?

**Comment by mblaschke** [comment]
Aus irgendeinem Grund ist bei einem Aufruf die Rootline leer, sollte eigentlich nicht sein. TYPO3 ist an einigen Stellen sehr konfigurierbar, daher tritt das leider auch nicht in allen Konstellationen auf und ein automatisiertes Testen ist im TYPO3 Umfeld oft recht aufwändig und schwer :(

Das Problem kam erst durch die Änderung, dass man Website-Root-Pages auch als Unterseiten haben kann, vorher wurde die Rootline falsch erkannt.

Ich kümmere mich um alle Probleme, sobald man mir sie melden :)

MetaSEO 2.0 wurde an vielen Stellen komplett überarbeitet und ich bin da schon seit einigen Monaten dran auch so ein paar grundsätzliche Probleme zu korrigieren.. dauert leider manchmal etwas, es ist nicht mein Vollzeitjob :)

PS: Jede Software hat eben auch als "stable" Fehler, vor allem wenn sie hoch konfigurierbar ist :)

**Comment by kurtvanc** [comment]
Ist ja eh verständlich. Finde das generell ein tolles Teil, bin schon sehr auf 2.0 gespannt.

Viel Glück und alles Liebe

**Comment by mblaschke** [comment]
Dann lass mich einfach heute noch die Version 1.0.7 veröffentlichen, die sollte das Problem zumindest beseitigen.

Hatte mich sehr auf das Refaktoring von 2.0 konzentriert.

**Comment by mblaschke** [comment]
Wird leider erst heute oder morgen abend ,sorry :(

**Comment by kurtvanc** [comment]
kein Problem!
Danke für alles!

**Comment by mblaschke** [comment]
1.0.7 ist im TER :)
Gab einige Probleme mit dem Upload :(

**Comment by mblaschke** [comment]
Kannst du bestätigen, dass das Problem behoben ist? Hab noch eine mögliche Problemlösung, die allerdings noch nicht im TER ist.
Ich bitte um Rückmeldung, sonst lad ich ASAP die 1.0.8 hoch.

**Comment by mblaschke** [comment]
Hab gleich mal 1.0.8 hinterher geworfen, hoffentlich ist das Problem nun wirklich behoben.

**Comment by kurtvanc** [comment]
Hallo!

Sorry, dass ich erst jetzt schreibe, war nicht im Lande.
Hab das Update gestern eingespielt und der Fehler tritt seitdem nicht mehr auf.
Super Arbeit, herzlichen Dank

LG Philipp
