### ISSUE TITLE
Sitemap issue within Google Webmaster Tools

### ISSUE THREAD

**Issue by MKchn** [mblaschke/TYPO3-metaseo#478]
**MetaSEO version**: 	3.0.0-dev
**TYPO3 version**: 8.7.1
**PHP version**: 7.1
RealUrl version (optional): 2.2.1

Hey i have a problem within the google webmaster tools. The error says:
Your sitemap is obviously an HTML page. Please use a supported format for Sitemaps instead.

Doublechecked the realURL configuration and for me all is fine...
The sitemap can be found via:
www.netfactory.de/sitemap.xml

**Comment by thomaszbz** [comment]
A sitemap generated by metaseo should start with (generated with metaseo 2.0.4, latest Typo3 7.6):

    <?xml version="1.0" encoding="UTF-8"?><sitemapindex xmlns=

The sitemap you provided starts with

    <?xml version="1.0" encoding="UTF-8"?><head/><sitemapindex xmlns=

... which in turn means that the `<head/>` tag should not be there.

Now that your sitemap.xml eventually is stored somewhere and therefore could be outdated or originate somewhere else, could you please check the sitemap provided in metaseo's backend section? Should be something like `http://www.netfactory.de/?id=X&type=841132` with `X` for your root page id.

I tried to reproduce this against TYPO3 8.7.1, PHP 7.0.16, latest metaseo 3.0.0-dev, but could not reproduce the head tag. For me, the output was as expected:

    <?xml version="1.0" encoding="UTF-8"?><sitemapindex xmlns=

Could it be that you have some piece of software running that tries to heal html syntax?

**Comment by thomaszbz** [comment]
Content-Type is defined in https://github.com/mblaschke/TYPO3-metaseo/blob/feature/8lts/Configuration/TypoScript/setup.txt#L556

That works great in TYPO3 7.6. In 8.7.1 LTS however, I get a 

    Content-Type: text/html; charset=utf-8

**Comment by thomaszbz** [comment]
@MKchn Please update from branch feature/8lts and see if the http header for the content type is right (F12 key in your browser) and fixes this issue.

**Comment by MKchn** [comment]
Works fine after updating. No more <head/> Tag in the sitemap.

**Comment by thomaszbz** [comment]
Headers also look as expected:
![auswahl_317](https://cloud.githubusercontent.com/assets/11200727/26537505/748a5ffc-4440-11e7-931a-1de148891c96.png)
