### ISSUE TITLE
Linkgeneration - Metatag Next, Up, Prev bei Multisites

### ISSUE THREAD

**Issue by 2kone** [mblaschke/TYPO3-metaseo#5]
Automatische Metatag Generierung Next, Up, Prev bei Multisites Nicht korrekt. 
Auf Root Ebene wird die nächste und vorherige Seite in die Metatags geschrieben.

Beispiel:
- foo.de
  -> ...link rel="next" href="http://bar.de" ...
- bar.de
  -> ...link rel="prev" href="http://foo.de" ...

Bitte nur auf die aktuelle Root-Seite beschränken.

**Comment by mblaschke** [comment]
Habe gerade eine potenzielle Fehlerkorrektur in den "develop"-Branch eingespielt.
Kannst du das mal testen, ob das nun besser ist? Danke :)
