### ISSUE TITLE
Clean standalone tags

### ISSUE THREAD

**Issue by al-Iskandar** [mblaschke/TYPO3-metaseo#50]
Since the deprecation of config.xhtml_cleaning there is a problem with getting XHTML documents clean in Typo3. So it is necessary that the extensions produce clean code by itself.
This means that standalone tags should get closed correctly like
<meta name="robots" content="index,follow" />

Till now I can clean it by config.xhtml_cleaning, but it is now just a feature of compatibility6

**Comment by mblaschke** [comment]
Already fixed in 2.0 with commit 1c00ab5652b2ae64e10767a84aa124ef07e0801f (current develop branch)
