### ISSUE TITLE
Sitemap contains hashes when used with CoolUri

### ISSUE THREAD

**Issue by thomaszbz** [mblaschke/TYPO3-metaseo#505]
reported by @DanPii 

Hi,
I have the same issue. 
Typo3: 7.6.15
MetaSEO: 2.0.3, just updated to 2.1.0.
cHashIncludePageId = 1

In my case I get different random (hased?)URLs.

- Some URLs are connected to the extension coolURI. Every time I open a site from within the backend via "view webpage" or "save and view page" (after editing content) Typo3 opens the page like this: domain.org/index.php?id=616&ADMCMD_cooluri=1
At the same time I get an sitemap entry like this:
![sitemap-urls-cooluri](https://user-images.githubusercontent.com/16837118/30000410-3f197cfc-9028-11e7-80bc-9eee8bbd4db4.jpg)
- with the other URLs, I don't know where they are coming from. Other extensions, included iframes, no idea. E.g.:
![sitemap-urls-ohter](https://user-images.githubusercontent.com/16837118/30000430-be5e8d36-9028-11e7-8d61-6b9f793769ed.jpg)

Is there a way to avoid / block those links? 
Or can I put them on the blacklist via wildcards or typoscript?

Thanks 
Daniel

**Comment by danpii** [comment]
Hi Thomas,

you were correct. This was indeed a CoolUri problem. 

In case someone else has the same problem, this is how I fixed it:
In CoolURIs config file (CoolUriConf.xml) you have to move this part:
```
<part>
    <parameter>cHash</parameter>
</part>
```

into `<predefinedparts>`

This excludes the hashes from CoolUri URLs.

More info in CoolUris Docs:
https://docs.typo3.org/typo3cms/extensions/cooluri/ChashIssue/Index.html

Ticket can be closed.

Thanks
Daniel

**Comment by thomaszbz** [comment]
@DanPii Thank you for reporting back.
