### ISSUE TITLE
Blacklist für Pages with Parameters

### ISSUE THREAD

**Issue by Domtaholic** [mblaschke/TYPO3-metaseo#531]
**MetaSEO version**: 3.0.0

**TYPO3 version**: 8.7.19

**PHP version**: 7.1.17

Hey,

we got many Extensions for a big company site, we work a lot with parameters here, cause you can filter for persons and so on.

Our SEO guys do complain about the generated sitemap cause there are a lot of pages wich include these parameters.

Example: http://xx/xx/xx/overview.html?retailer=71887&cHash=b1n5923sb8293c31c7258476fe127b1c

They only want to have clean urls without any parameters. 

To achive this i tried the following: 

`plugin.metaseo.sitemap.index.blacklist = /\?/`

Is there another way doing this or is my regex wrong?

Any help here would be great ;)

Thanks

Btw: Thanks for this great Plugin ;) really appreciate it

**Comment by j4k3** [comment]
The blacklist parameter expects an array, the patterns are checked against php PCRE. I was looking to do the same and this works for me:

    plugin.metaseo.sitemap.index.blacklist.10 = /(.*)\?(.*)/
