### ISSUE TITLE
Inherited page title prefix/suffix are not taken into account, if in a deeper page branch

### ISSUE THREAD

**Issue by PeaceSfiSh** [mblaschke/TYPO3-metaseo#57]
Within the given conditions the suffix and the prefix of a page title is not taken into account.
## Page tree

```
root (site title: My Company)
  |- Products (suffix: Our Products)
    |- Special Products (suffix: Automation products)
  |- bla
```
## Title results

Products: _Products Our Products: My Company_
Special Products: _Special Products Our Products: My Company_
## Conclusion

The suffix "Automation products" will never be used, because the higher level suffix is the first choice
## Result

Make the prefix/suffix usage more configurable.
1. use always the first x-fix in rootline (default)
2. use always the last x-fix in rootline (IMHO the most expected behavior)
3. allow chaining of the x-fix to create a breadcrumb-like page title (extensive)

**Comment by thomaszbz** [comment]
Reproduced. Not having case 2 seems indeed like a bug to me.

The existing code terminated on first occurance of a suffix or prefix:

                        if ($pageTitlePrefix !== false || $pageTitleSuffix !== false) {
                            // pagetitle found - break foreach
                            break 2;
                        }

... thereby the order was along the root line, but from root down to the children.

Plus, does this assume that prefix and suffix are always set at the same level of the tree. Which might not hold true.

I think, to cover case two and still be efficient, we mainly want to change the order to traverse the root line. That said, we can still determinate on first occurance.

**Comment by thomaszbz** [comment]
I just looked it up: The Inheritance mode already exists in the gui and is accessible via page properties:
![auswahl_263](https://cloud.githubusercontent.com/assets/11200727/25403637/479432c8-29fd-11e7-8cf6-3bc4782bafde.png)
