### ISSUE TITLE
SectionLinks: start points to root page instead first element of the sequence

### ISSUE THREAD

**Issue by rkoenig85** [mblaschke/TYPO3-metaseo#59]
Hi,

if the page is a subpage of a menu-seperator oder folder, the tag "<link rel="up" href="..../footer-navigation/">" is wrong.
The URI was generated by the pid of the page (MetatagPart.php:464). There is missing a check for the page-type (e.g. menu-seperator/storage folder).

Regards

**Comment by mblaschke** [comment]
Is is still valid for MetaSEO 2.0 (develop branch)?

**Comment by thomaszbz** [comment]
duplicate: https://forge.typo3.org/issues/66947

**Comment by thomaszbz** [comment]
Test against TYPO3 7.6.14, metaseo 2.0.1:

When a normal page (30) is surrounded by two menu separators(29 and 31), then the following entries disappear:

    <link rel="prev" href="http://172.17.0.2/index.php?id=29">
    <link rel="next" href="http://172.17.0.2/index.php?id=31">
