### ISSUE TITLE
why must pages be 100% cachable to be added to the sitemap?

### ISSUE THREAD

**Issue by Goltergaul** [mblaschke/TYPO3-metaseo#61]
As soon as one page contains one content element that is not cachable, the page is not added to the sitemap urls. Why is that? The page is still there and should be indexed by google...

**Comment by mblaschke** [comment]
I'm trying to prevent the manipulation of external urls:

It's not easy to check if one url is generated from TYPO3 or generated by some external resources (eg. your competitor), there is no easy way to detect this.

eg. which url is valid?
http://www.example.com/foobar/
http://www.example.com/foobar/?foo=bar
http://www.example.com/?id=123
http://www.example.com/?id=123&foo=bar

The `foo=bar` URLs should be invalid (also the chash is invalid) and not be indexed in TYPO3 to avoid duplicate content.
So MetaSEO checks if one page is cacheable (fully valid url with (!) valid chash) and only if this condition is true the page is indexed.

One solution would be to build a complete scheduler based indexer :(

**Comment by Goltergaul** [comment]
ok i see. Would it be possible to allow indexing Pages with INT_SCRIPTs on them? currently the following code prevents that from happening:

    // dont parse if page is not cacheable
    iif (!$GLOBALS['TSFE']->isStaticCacheble()) {
        return FALSE;
    }

Or do we have the same problem then? Or maybe we can check if there are no GET Parameters that are not included in the url itself. In that case it would be safe to index the page, right?

**Comment by mblaschke** [comment]
Please update to latest `develop` revision and set either or both `plugin.metaseo.sitemap.index.allowNoStaticCachable` or `plugin.metaseo.sitemap.index.allowNoCache` to 1 (TS constants)

**Comment by Goltergaul** [comment]
Thank you! (y)

**Comment by thomaszbz** [comment]
@Goltergaul just for the record: Was the issue fixed via 2c064fe?

**Comment by thomaszbz** [comment]
I assume this has been fixed. With the new config variables it looks more like a new feature.
