### ISSUE TITLE
sitemap hat nur einen Record

### ISSUE THREAD

**Issue by halione** [mblaschke/TYPO3-metaseo#62]
habe eine Frage zu deiner Extension die ich in der aktuellen Version 1,0.8 auf Typo3 6.3 LTS einsetze und RealURL in v 1.12.8.
Die Seiten sind nicht auf "no cache" gesetzt und werden gecached.

Ich bekomme leider nur einen Record in meiner Sitemap (index.php?id=1&type=841132) ausgegeben. Und dieser Record scheint die Sitemap selbst zu sein:( 

Im SEO > Control Center bei mir keine Domain… muss ich diesen Wert befüllen, bzw. eine domain record anlegen? Hatte das mal testweise gemacht allerdings hat dann mein realurl gestreikt und angefangen simulate static documents zu verwenden.
Unter „SEO > Sitemaps" hat er ca. 50 Einträge gefunden, und beide haken sind grün. Allerdings werden diese halt nicht in der sitemap ausgespielt.

**Comment by mblaschke** [comment]
Ganz sicher, das die URL auf die Sitemap zurück verweist und nicht auf eine Unterseite (&page=1)? Ruf mal genau die URL auf und schau mal was da kommt.

Die Sitemap verwendet eine sogenannte "sitemapindex"-Seite, da eine einzelne Sitemap in der größe Limitiert ist und man so mehrere "urlset"-Seiten verwenden kann.
Dies ist auch im Sitemap-Standard niedergeschrieben :)

PS: Das steht auch in der Doku drin ;)

**Comment by halione** [comment]
Ok, die page mit der id=1 ist meine root Seite welche gleichzeitig auch meine Home Seite ist.

**Comment by mblaschke** [comment]
Das ist auch ok, was passiert aber wenn du in der sitemap.xml die ausgegebene URL aufrufst?

**Comment by halione** [comment]
Dann kommt die sitemap so wie es scheint:)
Muss das so sein, denn diese funktioniert dann ja nur mit dem cHash richtig, und dieser kann sich ja ändern?

PS: die txt Variante wird korrekt ausgegeben mit: index.php?type=841131

**Comment by halione** [comment]
Oder ist dieses Format richtig und Sinnvoll, da wir mehrere Sitemaps haben können und diese dann in der sitemapindex als mehrerer sitemaps erscheinen?
Wenn dem so ist dann gehe ich davon aus das Google auch damit klar kommt ?

**Comment by mblaschke** [comment]
Es ist sinnvoll, eine Sitemap-Seite darf nur eine begrenzte Anzahl von Links haben. MetaSEO gibt die Sitemap so aus, wie es auf http://www.sitemaps.org/de/protocol.html#index beschrieben ist.
Google liest natürlich die Index-Seite korrekt aus und es wird auch in den Webmaster-Tools korrekt aufgelistet.

Große Seiten erreichen schnell mehrere hundert MB an Sitemap.xml, ohne Index-Seite wäre ein performantes Verarbeiten der Sitemaps bei Google nicht zu gewährleisten. Deshalb gibt es von Google ein Limit von 10MB bzw. 50.000 Einträgen.

PS: Der chash hat keinen Einfluss, dieser wird korrekt generiert. Dieser ändert sich eigentlich auch nicht laufend, da die Parameter der Sitemap sich nicht ändern. Aber er kann zur Prüfung verwendet werden, ob der Link von TYPO3 generiert worden ist.

**Comment by halione** [comment]
Danke schön!
Dann funktioniert es ja doch:)

**Comment by halione** [comment]
Hallo,

was muss ich tun um die sitemap neu zu generieren?
Habe meine RealUrl Paths und den Cache geleert.
Allerdings bleibt die Sitemap immer noch dieselbe??

**Comment by mblaschke** [comment]
Die Seiten werden beim Cachen der Seiten indiziert, wenn du den FE-Cache löscht dann müssen nur alle Seiten neu aufgerufen werden.

**Comment by halione** [comment]
Ok, nun hate s geklappt, lag wohl doch am cache....
