### ISSUE TITLE
Page-ID in sitemap.xml

### ISSUE THREAD

**Issue by thomaszbz** [mblaschke/TYPO3-metaseo#66]
As of 2697c177b3d39f83bf0dc83521207d17d146b850, I found entries like

```
<loc>https://www.example.com/67/</loc>
```

in the sitemap.xml when using realurl.

As far as I can see, the corresponding speaking url is also listed, e.g. 

```
<loc>https://www.example.com/speakspeak</loc>
```

Realurl is not mapping /67/ to /speakspeak/ which basically means that google sees duplicate content. Of course, the missing mapping of /67/ seems to be realurl related, but why should metaseo show it in the sitemap?

**Comment by mblaschke** [comment]
Metaseo can't see if a url is duplicate or not - maybe we need a scheduler task for this but not while indexing because this can be a heavy task.
The best way to prevent this is to fix the realurl/url generation issue :(

**Comment by thomaszbz** [comment]
yepp, it's all in realurl.

There's an extension forcerealurls, but it's outdated. Plus, it does not change a lot in respect to duplicate content in the sitemaps of metaseo.

**Comment by thomaszbz** [comment]
There is already a canonical-URL handling in MetaSEO which is working properly in the way that pages with URL example.com/?id=67 and example.com/67/ return the speaking URL as the canonical URL.

Can't we just reuse this canonical-URL when indexing? Can it also be applied for subpages in the way that we give TYPO3 CMS a link and get the corresponding canonical URL (if it's not overridden by MetaSEO)? If it's overridden by MetaSEO, we could take that URL instead.

If we can, we could index canonical URLs uniquely so that other URLs would collide with canonical URLs and therefore not be indexed.

**Comment by mblaschke** [comment]
There are two hooks:
- Page indexing hook which indexes the current url (and uses the canonical url thing)
- TypoScript indexing hook which is indexes the generated url

The last hook is optional but is a fast way to speed up sitemap indexing. If RealURL is generating a valid url it's quite hard to prevent indexing of this URL because it's a valid url generated from the TYPO3 system.

Maybe we can do some duplication checks but this can be tricky.

**Comment by thomaszbz** [comment]
This issue got fixed in the meantime in respect to my use case. RealURL and TYPO3 core fixed a _lot_ in that respect in recent versions (I use RealUrl 2.1.5 and TYPO3 6.2.29+).
