### ISSUE TITLE
Use config.doctype in isHtml5()

### ISSUE THREAD

**Issue by thomaszbz** [mblaschke/TYPO3-metaseo#69]
Please merge  PR #46 before 2.0.0 is to be released.

I retested 3a10d8feaa8369d77f635d5b06f4685d914921d1 and isHtml5() always returns null because the array entry does not exist. So #46 is better than the wrong code we have right now.

Btw. I found the current solution by var_dumping the typo3 arrays. Typo3 documentation is really poor here.

**Comment by thomaszbz** [comment]
I was wrong here: I had some misconfiguration in ts-setup after doing some consolidation.

Issue can be ignored and closed.

**Comment by mblaschke** [comment]
What about the PR #46?
