### ISSUE TITLE
Doctype heuristics for custom doctype

### ISSUE THREAD

**Issue by thomaszbz** [mblaschke/TYPO3-metaseo#70]
I did not test it yet, but I think that Typo3 CMS is allowing to set custom doctypes instead of constants which Typo3 CMS understands e.g.

    <!DOCTYPE html plus something stupid>

instead of

    html5

Typo3 reference says

    If set, then a document type declaration (and an XML prologue) will be generated.
    The value can either be A COMPLETE DOCTYPE or one of the following keywords:
    xhtml_trans for the XHTML 1.0 Transitional doctype.
    xhtml_frames for the XHTML 1.0 Frameset doctype.
    xhtml_strict for the XHTML 1.0 Strict doctype.
    xhtml_basic for the XHTML basic doctype.
    xhtml_11 for the XHTML 1.1 doctype.
    xhtml+rdfa_10 for the XHTML+RDFa 1.0 doctype.
    html5 for the HTML5 doctype.
    none for no doctype at all.
    
    Note
    
    Keywords also change the way Typo3 generates some of the XHTML tags to ensure valid
    XML. IF you set doctype to a string, then you MUST also set config.xhtmlDoctype (see below).

Basically this means that IF a custom doctype string is set, the developer needs to precise which doctype was ment. It can be specified for XHTML in xhtmlDoctype:

    xhtml_trans for XHTML 1.0 Transitional doctype.
    xhtml_frames for XHTML 1.0 Frameset doctype.
    xhtml_strict for XHTML 1.0 Strict doctype.
    xhtml_basic for XHTML basic doctype.
    xhtml_11 for XHTML 1.1 doctype.

However, html5 is not listed here (and it's also not XHTML). But now, there's also XHTML5 in the W3C Recommendation:

    This specification defines version 5.0 of the XHTML syntax, known as "XHTML 5".

I can't find a way the developer can specify HTML5 usage when he sets a custom doctype string. It's really ugly misuse of config variables. The custom doctype string could be defined in a separate variable, e.g. "customDoctypeString". I think the variable config.xhtmlDoctype is totally obsolete because all its constants are already defined for config.doctype. It's nothing else than a workaround for bad design.

Basically, what we need to be aware of is that custom doctypes are not properly supported, neither by Typo3 CMS nor by metaseo. Maybe we should file a bug report to Typo3 CMS Core. Otherwise it remains in the next LTS for another ~3 years. What do you think?

Old versions of Typo3 CMS also allowed the keyword

    html_5

which is deprecated since 4.5 and removed in 4.7.

Btw. I wonder why they did not use PHP constants for all the doctype keywords. We could easily adopt them in an extension like metaseo and be up-to-date whenever they change the keyword.

http://www.lake-studio.de/typo3/typo3-4-7-x-html5-doctype
https://forge.typo3.org/issues/25944
http://docs.typo3.org/typo3cms/TyposcriptReference/Setup/Config/Index.html#doctype
https://gutschik.com/gitlab/gutschik/typo3/commit/ba0989405e0cc1424cd672a8feb3c4fcb3601ba7.patch
http://www.w3.org/TR/html5/introduction.html#html-vs-xhtml

**Comment by mblaschke** [comment]
Should be fixed with db2100c911bbdbdc89f3e7ef3bba1c0df9db6df9

**Comment by thomaszbz** [comment]
Yes, should be better now. Still, I think that the custom doctype string is config variable misuse in the TYPO3 core, but for instance we can't improve that. Would be ways easier if the user could specify a doctype constant in config.doctype and specify a custom doctype string somewhere else.

Issue can be closed. We'll need to look at that again as soon as XHTML5 is supported officially. As far as I see it has just very low priority so far.
