### ISSUE TITLE
[feature] exclude pages from sitemap

### ISSUE THREAD

**Issue by erredeco** [mblaschke/TYPO3-metaseo#71]
Honestly I don't remember if it is already present,  if not please add the possibility to exclude pages from the xml sitemap. 
I've seen that Dulepov's extension does that using the no_search field of Pages 
Thanks

**Comment by thomaszbz** [comment]
Please try out if my workaround for separators from #24 is working for you. I think the requested feature of this issue exists already in older versions, at least in develop branch (the upcoming 2.0.0).

Workaround to get rid of menu separators in the sitemap.xml (should work with ANY page):

- In the backend, click metaseo on the left side
- click the menu separator page in the page tree
- click "searchengine information" in the top dropdown
- in the table, set "excluded" to "true".

**Comment by erredeco** [comment]
My question was about the possibility to decide wether a page is in the sitemap or not. I see that this is done with the "Exclude page from SearchEngines" checkbox.
so this can be closed. Anyway thank you for your answer

**Comment by thomaszbz** [comment]
That's another way which is probably not specific to metaseo.

**Comment by erredeco** [comment]
the field in database is called "tx_metaseo_is_exclude"  ;)

**Comment by thomaszbz** [comment]
Then, it's metaseo specific ;)

**Comment by mblaschke** [comment]
- It's possible with "Exclude page from SearchEngines" in SEO tab (page settings)
- Blacklisting in sitemap module
- In TypoScript with "plugin.metaseo.sitemap.blacklist"

**Comment by thomaszbz** [comment]
can be closed

    so this can be closed. Anyway thank you for your answer
