### ISSUE TITLE
Problems with metaseo classes in scheduler

### ISSUE THREAD

**Issue by al-Iskandar** [mblaschke/TYPO3-metaseo#72]
The actual version breaks the scheduler in the backend by a class problem. It was anything with "Metaseo\Metaseo\Scheduler\Task\GarbageCollectionTask" called by the scheduler.php (ca. line 106) But I do not find anymore the error message and I am happy that my installation is working again.

I could only solve the problem by deleting manually all three metaseo entries in the scheduler table in the database.

**Comment by thomaszbz** [comment]
Maybe you find some error message in your logs?

- typo3 log (backend/log)
- apache error log

When did the error occur? Directly after switching from 1.0.x to develop?

Did you see an error message like

    Cannot use TYPO3\CMS\Core\Utility\GeneralUtility as GeneralUtility because the name
    is already in use in .../metaseo/Classes/Utility/FrontendUtility.php on line 27

Was it working after you flushed caches in the backend, including "flush system caches"?

**Comment by al-Iskandar** [comment]
The error message I saw when I had activated displayErrors, but I cannot reproduce it now, because I deleted the breaking dataspace entries. But the entries had all a file with an array in the end which contained the class name near at the beginning.
I clared the caches by the functions in the backend, in the install tool and even by deleting the contents of typo3config.
The error was only visible when I tried to access the scheduler section of the backend. When I saw only a blank page in the "frame" I switched to displayerrors. After deleting the entries in the database, everything was working.
Updating from Typo3 v7.2 to v7.3 needed a whole weekend. As you see in this extension, but also with other extension, it was a big fight to get the system running again.

**Comment by thomaszbz** [comment]
It's hard to reproduce it that way. Could you please describe step by step what you where doing?

- Which version of metaseo/tq_seo did you start with?
- Which version of TYPO3 did you start with?
- Which was the order of corresponding updates you performed (TYPO 3 and metaseo)?
- Which caches did you clear when?
- Which database entries did you clear when?
- When did the error occur for the first time?
- When did the error disappear (in the order of the actions you performed).

Plus, the error message is lost. For the moment we only know that something went wrong.

- It could be namespace related, perhaps combined with autoloading/caching (I have seen that by myself when I updated from 1.x to develop).
- It could be database caching related. 
- Plus, it could be database tupels which did not match to the data metaseo expected. Therefore we need to know all the versions of tq_seo/metaseo you had installed before. Could be a breaking change in the past or it could be a missing database migration step when you upgraded somewhere in between.

**Comment by al-Iskandar** [comment]
I used tq_seo since the time of Typo3 v4.5. I migrated to metaseo during Typo3 v6.2 (repository version 1.0.x). Because of technical problems with the migration tool I migrated manually. This means I created the three scheduler entries fresh.
I do not know whether I entered the scheduler section after I moved to Typo3 v7.2. I found the issue just after moving to Typo3 v7.3 (without compatibility6) and metaseo 2.

If it is not reproducible at the moment, I will take care, when other problems are solved.

**Comment by mblaschke** [comment]
The problem is that TYPO3 is using a serialized PHP string for "scheduler storage" and if there is any typo/modification/renaming the scheduler task is broken :(

**Comment by al-Iskandar** [comment]
OK
After creating the tasks again, they seem not to make problems again.
I see only a fundamental problem. An average user without deep experience of programming can not see when updating of Typo3 Core brings such a break in the scheduler. Because scheduler is a core extension, I think the upgrade routine should in such cases delete scheduler record with integrated files. But this ticket should open a programmer who can explain it to other programmers.

**Comment by thomaszbz** [comment]
Hopefully they'll find us on github ;) and come up with an error message...

I guess most users will update when 7 LTS is released.

If scheduler task records are broken by TYPO3 core in general this would have to be be reported to the issue tracker of TYPO3 core. For the moment there is no strong evidence for that.

Can this issue be closed?

**Comment by al-Iskandar** [comment]
The last message was an implicit closing from my side
