### ISSUE TITLE
Pagetitle Suffix is shown twice

### ISSUE THREAD

**Issue by markussoeth** [mblaschke/TYPO3-metaseo#75]
The page title-tag contains now two times the "title of website".
even when plugin.metaseo.pageTitle.sitetitle only is set and "title of website" in Template is empty.
Version 1.0.8

**Comment by mblaschke** [comment]
Duplicate with #60?

**Comment by markussoeth** [comment]
Sorry YES. 
Did not saw that even with searching through issues..

**Comment by mblaschke** [comment]
Sorry, but it's a core bug :(
