### ISSUE TITLE
Typo3 CMS 7.3.1 causes error

### ISSUE THREAD

**Issue by prentice87** [mblaschke/TYPO3-metaseo#83]
Frontend Error: "Could not analyse class:Metaseo\Metaseo\Connector maybe not loaded or no autoloader?"
http://typo3.org/go/exception/CMS/1289386765

Is there maybe some fix where i just have to change one line of code somewhere? Would like to continue using this aweseome Plugin :)

**Comment by mblaschke** [comment]
Which version? 1.x or 2.x?

**Comment by prentice87** [comment]
Sorry 2.0.0 I think 1.x wouldn't work with 7.3.1 anyways, right?

**Comment by mblaschke** [comment]
There was a PR some days ago which fixed the issue. Did you use the newest develop version?

**Comment by prentice87** [comment]
Perfect, works like a charm :) Maybe make it Version 2.0.1 or something? I would've tried that if it had been a different Version from mine :)

**Comment by mblaschke** [comment]
There is no official 2.0.0 yet.
Do you use composer?

**Comment by prentice87** [comment]
Not with Typo3 yet. I'm still suffering through learning how to actually make an Extension and trying to learn Zend2 at the same time...all while getting through a huge project^^ But i will try it if I find some time :)
