### ISSUE TITLE
Don't index sitemap

### ISSUE THREAD

**Issue by thomaszbz** [mblaschke/TYPO3-metaseo#84]
Doing a google query

    site:www.example.com

google lists the sitmaps as if they were normal pages.

This seems to lead to the problem that google is interpreting the text (inside xml tags) as content which itself seems to lead to the problem that google is also using that "content" to generate keywords for the page in google search console. I get entries like

    daily 	
    https 	
    09t23 	
    26t06 	
    26t10 	

in google's keywords list. Note that google does not extract dates here. Also note that the entry "daily" clearly indicates that it comes from the sitemap.

I suggest to exclude the sitemaps from indexing by using an additional http header:

    X-Robots-Tag: noindex

Currently, I'm testing a corresponding patch to see if google's keyword list changes.

This should be fixed because tolerating unwanted but high-ranked keywords is pretty much what SEO is _not_ about.

Keep in mind that #67 is about the date in search results which is another issue. Anyways, it seems to be possible that #67 might not be about date _formatting_ but about using another way to transmit dates (as already described). 

References:
https://developers.google.com/webmasters/control-crawl-index/docs/robots_meta_tag?hl=en

**Comment by thomaszbz** [comment]
Currently, I'm running a test for PR #85 to see how google handles the change.

**Comment by mblaschke** [comment]
No errors in webmaster tools? Doesn't prevent this google from using sitemap.xml?

**Comment by thomaszbz** [comment]
Right now, there's no error in webmaster tools:

    Index: /?id=2&type=841132
    Diese Sitemap-Index wurde am 15. Juli 2015 eingereicht und am 15. Juli 2015 verarbeitet.
    
    Sitemap-Fehler
    Fehlerdetails: Es wurden keine Fehler gefunden
    
    Indexfehler
    Fehlerdetails: Es wurden keine Fehler gefunden. 

I'll see what google is actually doing. For the moment, the sitemap still is in the search results.

Google can still _use_ the sitemap: There's a difference between noindex and nofollow.

I want google to

- read the sitemap and follow the links of the sitemap
- not index the sitemap
- not show the sitemap in search results
- not use the sitemap to generate (wrong!) keywords.

**Comment by thomaszbz** [comment]
I guess this can take endless: Quote: "Also, keep in mind that even if your robots.txt file is disallowing access to a URL, that URL may remain visible in search results despite that fact that we can't crawl it".
https://developers.google.com/webmasters/control-crawl-index/docs/faq?hl=en#h18

All I can say right now is that webmaster tools does not show any errors or blocked content after I had it running for about 3 weeks.

@mblaschke Can I merge it?

**Comment by thomaszbz** [comment]
Latest findings with the patch applied:

- webmaster tools does not show keywords extracted from sitemap any more.
- sitemap URLs are not part of the search results any more (when performing a google search query with ``site:www.example.com``.

It took google several months for these changes to take effect, but this may differ from site to site. I'm also not sure if the magic happened because of this patch or if google, overall, improved its "misbehaviour".

I'm going to merge this after testing against the latest version of metaseo again.
