### ISSUE TITLE
dc.subject: w3c validation error

### ISSUE THREAD

**Issue by thomaszbz** [mblaschke/TYPO3-metaseo#9]
w3c validation against HTML5 reports 
"Bad value DC.Subject for attribute name on element meta: Keyword dc.subject is not registered. A metadata name listed in the HTML specification or listed in the WHATWG wiki. You can register metadata names on the WHATWG wiki yourself."

Hint: there is a "dcterms.subject" Meta extension. Maybe this one should be used instead.

References:
http://validator.w3.org/
https://html.spec.whatwg.org/multipage/semantics.html#standard-metadata-names
https://wiki.whatwg.org/wiki/MetaExtensions

**Comment by thomaszbz** [comment]
tested version was 1.0.5

**Comment by mblaschke** [comment]
Fixed with #10
