### ISSUE TITLE
[TASK] refactor ajax backend

### ISSUE THREAD

**Issue by thomaszbz** [mblaschke/TYPO3-metaseo#92]
Issues:

- reduce duplicate code: method for ajaxSuccess and ajaxError
- unify message generation
- respect return data types of ajax methods (execute...)
- http status codes for errors (see https://dev.twitter.com/overview/api/response-codes)
- reduce code complexity
- exception handling
- easier translation

**Comment by thomaszbz** [comment]
@mblaschke What's the concept for Ajax error numbers like [0x4FBF3BD9]?

As far as I can see all the actions in MetaSeo.overview.js are checking for errors like

    var response = Ext.decode(response.responseText);
    if ( response && response.error ) {
        TYPO3.Flashmessage.display(TYPO3.Severity.error, '', Ext.util.Format.htmlEncode(response.error) );
    }

This might work better than before, because not all errors had this form in json.

For MetaSeo.sitemap.js I'm not sure. They had scalar return values true or false. Now it's all arrays with key 'error' or 'success'. You think it should work?

To be done:

- Set meaningful error messages, error numbers and http status codes everywhere in the ajax backend (http status code defaults to 400 for errors)
- Do something with the error number in the frontend
- Error handling in MetaSeo.sitemap.js?
- Test everything

**Comment by mblaschke** [comment]
IMHO we should kick/refactor the most stuff when switching to another framework (or update ExtJS)

the concept of these errors numbers was the attempt to have searchable error codes (for code search). the same way of unix timestamps in exceptions.
