### ISSUE TITLE
[TASK] typo in table definition

### ISSUE THREAD

**Issue by thomaszbz** [mblaschke/TYPO3-metaseo#96]
There's a typo in table definition:

    sitemap_priorty float DEFAULT '1' NOT NULL,
    sitemap_priorty_depth_multiplier float DEFAULT '1' NOT NULL,
    sitemap_priorty_depth_modificator float DEFAULT '1' NOT NULL,

should be 'priority'

Options:

- leave as is
- fix for 2.0.0
- fix in 2.1.0/3.0.0 (avoid schema changes in minor versions)

Do we already have other schema migration issues for 2.0.0? Then should can fix the typo now, combined with the other changes.

Btw @mblaschke, what's the concept for schema migration?

**Comment by mblaschke** [comment]
We can use the extension update feature for migrations.
We could fix this for 2.0 IMHO because it's a major update.

In migration we could check INFORMATION_SCHEMA about the existing of both (typo and fixed) attributes and transfer the old attributes to the new attributes.

**Comment by thomaszbz** [comment]
Found a piece of code for renaming attributes via class.ext_update.php at https://github.com/TYPO3-extensions/news/blob/master/class.ext_update.php#L203

**Comment by thomaszbz** [comment]
Tested develop 686f12f against TYPO3 6.2.17:

* Used metaseo 1.0.8 from master (via git)
* installed metaseo
* created page with priority 85
* checked out metaseo develop 686f12f
* Ran "Execute the update script" button in extension manager

Result message from the update script button:

> Update script for metaseo
> Renaming "tx_metaseo_setting_root:sitemap_priorty" to "tx_metaseo_setting_root:sitemap_priority":
OK!
> Renaming "tx_metaseo_setting_root:sitemap_priorty_depth_multiplier" to "tx_metaseo_setting_root:sitemap_priority_depth_multiplier":
OK!
> Renaming "tx_metaseo_setting_root:sitemap_priorty_depth_modificator" to "tx_metaseo_setting_root:sitemap_priority_depth_modificator":
OK!

* After that, ran table field comparison via install tool with result:

    ALTER TABLE tx_metaseo_setting_root CHANGE sitemap_priority sitemap_priority float NOT NULL default '1';
    Current value: float default NULL
    ALTER TABLE tx_metaseo_setting_root CHANGE sitemap_priority_depth_multiplier sitemap_priority_depth_multiplier float NOT NULL default '1';
    Current value: float default NULL
    ALTER TABLE tx_metaseo_setting_root CHANGE sitemap_priority_depth_modificator sitemap_priority_depth_modificator float NOT NULL default '1';
    Current value: float default NULL

* Applied changes in install tool
* checked priority from test page -> priority was still there (unchanged)

=> Patch seems to be valid, at least for this test scenario (6.2.17, update metaseo 1.0.8 -> develop 686f12f)

**Comment by thomaszbz** [comment]
Reexecution of the update script is handled correctly with OK-messages like

> Field tx_metaseo_setting_root:sitemap_priority already existing.

**Comment by thomaszbz** [comment]
The migration via "Execute the update script" button also works in TYPO3 7.6.2.

I could not install 1.0.8 because of compatibility issues to test the whole procedure. I strongly suggest to update metaseo before updating TYPO3 6.2 to 7.6.

**Comment by thomaszbz** [comment]
To sum up: User must run extension manager's "Execute the update script" when updating to develop 686f12f or later (e.g. 2.0.0 production)
