### ISSUE TITLE
[TASK] remove sanitizeSqlField/Table functions

### ISSUE THREAD

**Issue by thomaszbz** [mblaschke/TYPO3-metaseo#97]
User input for tables and attributes should never be processed for security reasons.

Therefore, the correct table/attribute name must be known _exactly_ by the code and then allows an exact match. Therefore, no sanitize will ever be needed because if it does not match _exactly_, then it's wrong.

To our luck these functions are never used in the code and we are safe here.

I'd like to remove these functions as they are not used and also should never be used.

**Comment by mblaschke** [comment]
Sometimes it's needed to have some dynamic table/attributes but if there is no usage we can safely remove this stuff.

This class is a duplication so there are methods without usage in this extension.
